### ISSUE TITLE
Default implementation of Serializer and Deserializer methods

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#1035]
Continued from #1033:

> It might also be useful to provide default implementations or helper functions for things that most formats are going to do the same thing with (eg numeric / floating point types).

@spease

**Comment by dtolnay** [comment]
In previous versions of Serde we used to provide default implementations and helper functions. It turned out there is no such thing as "most formats". Any default functionality we provide would apply to maybe 10% of formats and be actively hostile to 90% of formats -- because it makes it too easy to forget to override some incorrect behavior. Check out #219 for a previous discussion of this.

I think the recommendation is generally to find the format most similar to the one you are developing, and cherry-pick code from that. And if you are developing a format that is totally unlike any existing format, you would not have benefited from default functionality anyway.

A helper library for common data format functionality would be more appropriate! If you have ideas for it, I would love for you to own that (in its own repo).

**Comment by spease** [comment]
The helper library is an interesting idea. I'll keep it in mind, but I'm in the middle of a job search right now. There are some parts of the LVM library that I can see being broken away into something that would be useful for generic text format parsing, and patterns that can probably be refactored into macros.

**Comment by ysar** [comment]
> In previous versions of Serde we used to provide default implementations and helper functions. It turned out there is no such thing as "most formats". Any default functionality we provide would apply to maybe 10% of formats and be actively hostile to 90% of formats -- because it makes it too easy to forget to override some incorrect behavior. Check out #219 for a previous discussion of this.
> 
> I think the recommendation is generally to find the format most similar to the one you are developing, and cherry-pick code from that. And if you are developing a format that is totally unlike any existing format, you would not have benefited from default functionality anyway.
> 
> A helper library for common data format functionality would be more appropriate! If you have ideas for it, I would love for you to own that (in its own repo).

Sorry for necro'ing this closed issue. Is there a reason the default implementations for `Serializer` and `Deserializer` were altogether removed, rather than changed to returning an `Error`?

In the absence of defaults, one has to implement a `serialize_<T>` for each serde type, even the ones that should not be serialized into the format. E.g., for a serialization format that cannot accept `u64`, calling `serialize_u64` should error out. 

The pros: It would avoid a lot of boilerplate for simpler formats, or for just "trying serde out".
The cons: The error would be caught at run-time rather than compile-time.

Alternatively, could this be done via a macro? E.g., something like,

`serde_impl_invalid_serializer!(u64 u32 u16 u8)`

would generate a default implementation that would return an `Error` for those types.
