### ISSUE TITLE
Summary information about trait functions in the data format guide

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#1036]
Continued from #1033:

> It would also be good to explicitly link to or call out the summary information about the trait functions on the Deserializer trait:
> https://serde.rs/impl-deserializer.html

@spease

**Comment by dtolnay** [comment]
Could you clarify what you have in mind? Do you mean copy some of the Rustdoc of Deserializer trait methods from [here](https://docs.serde.rs/serde/de/trait.Deserializer.html) to [here](https://serde.rs/impl-deserializer.html)?

**Comment by spease** [comment]
Yes, though I was principally referring to the description of the 27 types that's also here:
https://serde.rs/data-model.html

I'd read some of the serde documentation originally when I started using Serialize/Deserialize, so I looked specifically for the stuff that answered the question "How do I start writing something that will deserialize from the text data?" or basically "How do I write a Deserializer?" and missed the data models page. In going back over the documentation, I see that there is a note in the front page for the "Writing a data format" section that the data models are the "second most important" so that is admittedly somewhat my fault for skipping around to try to find the most relevant data.

What I like about the reference page for Deserializer is that it starts to hint at what the particular deserialize_* functions want. Eg a struct is described as "heterogeneous key-value pairing" and the deserialize_* functions are described as "Hint that the Deserialize type is expecting..." although it does not say specifically that deserialize_bool will probably want to call visit_bool.

What still isn't clear from those pages, at least to me, is that you can use MapAccess instead of basically writing that out yourself. If not for the JSON example (the other link you posted) I would probably think that I needed to do all of that with parsing within the dserialize_struct function using the name/fields. Then would be totally lost about how to figure out what visit_* to call for each field (unless the format was self-describing and I could call deserialize_any).

MapAccess and the like seem kind of like seem sort of like black magic right now to me, that I have no idea what I can use where, and the only way I can learn what I can do is looking at what other people did in their format libraries, or maybe looking through the serde internal source code. I don't know of a list that links directly to the deserializers/serializers of other libraries using serde, so that approach seems very inefficient (even if there were, I would still prefer to have it documented in a single place in the API so it's O(1) to look up instead of O(N) to search projects).

Sorry these comments are long, hopefully these are helpful.

**Comment by dtolnay** [comment]
The three sections on what is the data model, API reference for Serializer and Deserializer, and example data format implementation, are intended to complement each other and definitely needed more cross linking. I added the problematic missing links in https://github.com/serde-rs/serde/commit/0fbf4d0c5d6cb20f95ff400b94361c3b35e7be69, https://github.com/serde-rs/serde/commit/a65950accaa97097ba7e19f88c4bb1eedc64b918, https://github.com/serde-rs/serde-rs.github.io/commit/65ae67efa4b9b575b846437967dd31949b0b3068. Thanks!
