### ISSUE TITLE
serialize_*_variant should provide a count of every possible variant for that enum

### ISSUE THREAD

**Issue by TyOverby** [serde-rs/serde#1068]
For example: 

```diff
    fn serialize_struct_variant(
        self, 
        name: &'static str, 
        variant_index: u32, 
+       variant_count: u32, 
        variant: &'static str,
        len: usize
    ) -> Result<Self::SerializeStructVariant, Self::Error>;
```

This would allow crates like bincode to pick the size of the datatype to encode the tag.  e.g. Serializing an enum with only 3 variants would let bincode encode this using a `u8`.

**Comment by dtolnay** [comment]
Closing because I don't intend to consider breaking changes, but here are two workarounds for now:

- Use a variable-length encoding that does not require knowing the total number of variants. A good majority of enums have 240 or fewer variants, so something like [this encoding](https://sqlite.org/src4/doc/trunk/www/varint.wiki) would be similarly cheap.

- Provide a custom derive that serializes enums as a tuple of `(index, contents)` where the index is an integer type of the right size given the number of variants.
