### ISSUE TITLE
Override serialization options

### ISSUE THREAD

**Issue by csharad** [serde-rs/serde#1129]
I have a situation where I have to serialize to different forms of the same struct. For a user facing response, I want to skip the password but when I am using it to store in Redis, I would like to include the password as well. To achieve that right now, I am creating another struct just for Redis.

    #[derive(Serialize)
    struct User {
        id: i32,
        username: String,
        #[serde(skip_serializing)]
        password: String
    }

Is there any form of switch where I can disable `skip_serializing`?

**Comment by oli-obk** [comment]
You could create a `Password` type whose `Serialize` impl checks some thread local global for whether it should be serializing passwords.

Other than that I don't know of any solution that works on a stable compiler.

**Comment by csharad** [comment]
How would it be implemented? The global variable would have to be mutated when called from request handlers and set otherwise in request guards (in Rocket). I don't think it would be atomic between multiple requests.

I was thinking of it as a new feature if there wasn't already.

**Comment by oli-obk** [comment]
@csharad yea, you'd need to do that manually and ensure correctness of the global in your own code.

I'm not sure how to add such a feature, since it would be purely a runtime decision in the `Serializer`. You could create a new `Serializer` (wrapper around another `Serializer`) that skips all fields named `password` and otherwise just forwards to the inner `Serializer`. But that's pretty hacky.

**Comment by csharad** [comment]
It seems creating duplicate struct would be easier.
I do not know how to macro but here is an idea. The struct could be duplicated with different options for serializing.
`#[alt = "[ { name: 'DupName', ignore: ['skip_serializing'] }, ... ]"]`

Anyways thank you.
