### ISSUE TITLE
Is it possible to serialize a referenced value which store data outside?

### ISSUE THREAD

**Issue by hh9527** [serde-rs/serde#1148]
```rust
#[derive(Debug)]
struct StringRef(usize); // it is an index of real value outside

#[derive(Debug, Serialize)]
struct Foo {
  name: StringRef; // in this struct, a reference is stored instead of real value
  // ...
}

impl Serialize for StringRef {
  fn serialize<S>(&self, s: S) -> Result<S::Ok, S::Error> {
    // but I need to serialize it as real value, not an index
    // **HOW-TO**
    s.serialize_string_ref(self.0)
  }
}

struct StringRefSerializer<'a, S> {
  // the mapper of index and real value will be stored in the wrapped serializer.
  // and also there is underlying serializer,
  names: &'a HashMap<usize, String>,
  underlying_serializer: S
}

impl<'a, S: Serializer> StringRefSerializer<'a, S> {
  fn serialize_string_ref(self, id: usize) -> Result<()> {
    let StringRefSerializer { names, underlying_serializer } = self;
    let name = names.get(&id).unwrap();
    underlying_serializer.serialize_str(name.as_ref())
  }
}
```

My question is at the place of **HOW-TO**, I can not got the context to construct a StringRefSerializer.
So, anyone can help me to do this? or is there a better approach to do this?

**Comment by Marwes** [comment]
Since `fn serialize<S>(&self, s: S) -> Result<S::Ok, S::Error>` is generic over the serializer `S` you won't be able to turn it into a `StringRefSerializer` (it could be any other serializer type as far as the code knows). So either you need to store that state in a thread local variable or you may want to look at https://github.com/Marwes/serde_state which mirrors the serde API but lets you pass a state along with the serializer. https://docs.rs/serde_state/0.4.3/serde_state/

**Comment by hh9527** [comment]
@Marwes thank you very much, i have tried serde-state as you suggested, it works! (though this crate is marked as experimental)

**Comment by Marwes** [comment]
@hh9527 Well, it is a patched version of serde which I published independently. Since most people won't need the stateful serialization it provides it is not quite worth bringing that complexity into serde proper. Instead I try to rebase it on serde master every know and then to keep it up to date with fixes and features.
