### ISSUE TITLE
serde_json flatten behave unexcept when duplicate field name in parent struct

### ISSUE THREAD

**Issue by wayslog** [serde-rs/serde#1190]
As we can see:

```rust
#[macro_use]
extern crate serde_derive;
extern crate serde_json;

#[derive(Debug, Serialize, Deserialize)]
struct Pagination {
    limit: u64,
    total: u64,
}

#[derive(Debug, Serialize, Deserialize)]
struct Users {
    limit: u64,

    #[serde(flatten)]
    pagination: Pagination,
}

fn main() {
    let u1 = Users {
        limit: 10,
        pagination: Pagination {
            limit: 100,
            total: 1000,
        },
    };
    let user_str = serde_json::to_string(&u1).unwrap();

    // output is: {"limit":10,"limit":100,"total":1000}
    // it's a wrong json format by JSON's specifications.
    println!("{}", user_str);

    // May panic there: ErrorImpl { code: Message("duplicate field `limit`"), line: 1, column: 19 }
    let u2: Users = serde_json::from_str(&user_str).unwrap();

    // May panic too: ErrorImpl { code: Message("missing field `limit`"), line: 1, column: 50 }
    let u10: Users =
        serde_json::from_str(r##"{"users":[],"limit":100,"offset":20,"total":10000}"##).unwrap();
}
```

By the way, can `serde` check if there are any duplicated fields and report them as a warning or an error?

**Comment by dtolnay** [comment]
I don't think we can detect this at compile time because macro expansion looks at only one struct/enum at a time in isolation.

The serialize behavior seems fine. Duplicate fields are not disallowed by JSON specification as far as I know. The deserialize behavior matches what happens with any #[derive(Deserialize)] impl that receives more than one of the same field, though your own Deserialize impl would be free to handle duplicates differently.

**Comment by wayslog** [comment]
Sure, there is no any rulers, you are right.

But `serde-json` can't decode well what it has encoded and panic at last.

**Comment by dtolnay** [comment]
Thanks for reporting an issue but let's plan to not fix this. I believe the legitimate use of duplicate fields across the outer and inner flattened struct is uncommon enough that we can ask them to implement their own Deserialize to handle it.
