### ISSUE TITLE
Structs with flattened fields are serialized and deserialized as maps

### ISSUE THREAD

**Issue by torkleyy** [serde-rs/serde#1346]
This causes problems for formats that use different syntax for structs and maps. Is there some way to fix it?

**Comment by dtolnay** [comment]
Rust structs with flattened fields are not "structs" by Serde's definition of "struct". A struct in Serde means that the fields are known at compile time. This is enforced for example by [`Deserializer::deserialize_struct`](https://docs.serde.rs/serde/de/trait.Deserializer.html#tymethod.deserialize_struct) which requires a `&'static [&'static str]` of the field names. But in a Rust struct with flattened fields, the Serialize impl of the flattened type can potentially insert any fields it wants at runtime.

RON could work around this by allowing deserializing Serde maps from RON structs, or I would be willing to consider a PR to support a compile-time declared set of what fields the flattened type is allowed to insert:

```rust
#[derive(Deserialize, Serialize)]
struct Main {
    #[serde(flatten(first, second))]
    required: Required,
    #[serde(flatten(third))]
    optional: Optional,
    some_other_field: u32,
}
```

**Comment by dtolnay** [comment]
Right, this would be for flattening types that have a compile-time knowable set of fields.

**Comment by RReverser** [comment]
Just ran into the same issue with [serdebug](https://github.com/RReverser/serdebug).

@dtolnay I see there is already `deserialize_identifier`. Could we just add a counterpart for it in `Serializer` and for flattened structs continue to use `serialize_map` but use that new `serialize_identifier` for keys? I imagine that would be easier to use than enumerating flattened fields by hand.

**Comment by RReverser** [comment]
Ideally, I would also add `Token::Ident` to distinguish these from regular strings, but that would be a breaking change, so I guess not an option.

**Comment by dtolnay** [comment]
Considering this issue again, I would prefer to simply leave this as a known issue affecting a subset of data formats. There are many different choices for how a flatten attribute could be implemented, the most powerful of which might be requiring some flatten-specific trait to be implemented for any type which you want to be able to flatten, but I believe the current implementation built around just the Serialize and Deserialize traits is making the correct tradeoffs.

**Comment by Mingun** [comment]
Whether it is possible to call hinted deserialising methods if `serde(flatten)` is applied only to structures (but not to `HashMap`, for example, when the count of fields can be unknown that how I understand, is the main motivation when deserialising such structures as map)? It can be implemented also as in this case we will make manually -- to implement deserialising for the generated intermediate structure
```rust
#[derive(Deserialize)]
struct SomeGeneratedStructureName {
  /// This field does not even require renaming in style
  /// ```
  /// #[serde(rename = "b")]
  /// some_generated_name: bool
  /// ```
  /// as it is already unique, otherwise deserialising would not work absolutely.
  /// And I think that `serde(flatten)` already prohibits identical names of fields
  b: bool,
  //...other fields from Outer and Inner
}
```
and its conversion to the `Outer`

**Comment by RReverser** [comment]
@dtoln

**Comment by dtolnay** [comment]
@RReverser -- I acknowledge that suggestions have been made, but I would still make the choice of leaving this as a known issue rather than pursuing any of them. It is necessary to be strategic about which issues to address. The state of the world is that there are maybe 100 known ways that Serde could be extended to cater to small groups of users; each one involving minor API additions here or there. If we simply work through and do all 100 new features, the entire thing becomes a disaster suitable for nobody. As such, it is inevitable that suggestions which may seem reasonable and well justified in isolation are going to get dropped, and I don't consider an obligation to explain individually why we can't pursue each one.

**Comment by dtolnay** [comment]
None of the current suggestions would be accepted as a PR.

**Comment by Mingun** [comment]
But why? My suggestion has some problems? In my opinion not. Closing of an issue without explanations in my opinion nonconstructive approach -- to these you only push away potential collaborators. For me, for example, desire to help the project which so fastidiously refuses the help of those who are interested in it absolutely vanishes

**Comment by dtolnay** [comment]
@Mingun -- You are welcome to contribute on any of the remaining open issues! It is unfortunately not realistic to permit every contributor to add what they want into a mature project; I hope you understand.
<br>

- The method you described in https://github.com/serde-rs/serde/issues/1346#issuecomment-451722455 is not possible to implement under the current model for procedural macros in Rust, which are restricted to operating on individual types in isolation without knowing what fields exist on any other types until runtime.

- The behavior around `bool` that you described in https://github.com/serde-rs/serde/issues/1346#issuecomment-450728864 is not related to this issue but to #1183, which remains open.

**Comment by Mingun** [comment]
@dtolnay, I thank for explanations -- now clearly that the problem depends on other problem in rust. If issue in the rust repository for that not yet exists, then it should be open that instead of close this issue -- because from closing of an issue the problem of developers did not go out! Besides, it turns out that another serde bug is related with it: the `serde(flatten)` attribute does not check that fields in structures will be unique and allows to generate incorrect result: [playground][flatten]. However, `serde(rename)` also suffers from the same problem: [playground][rename]

[flatten]: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7f2537d16eba852a988c0a2026eae8f1
[rename]: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4d4f2fa24c0df4c07bfb66ecb90cec46

**Comment by RReverser** [comment]
Ugh, today ran into this again with yet another target that has different representations for structs and maps, resulting in incompatibilities :(

@dtolnay If you feel strongly about not fixing this issue, could we maybe soft-deprecate `serde(flatten)`, and move current implementation to a separate proc-macro crate as you suggested for few other issues?

That would hopefully bring more attention to differences for users, and would make this less of a footgun for `Serializer`/`Deserializer` authors like me.

**Comment by RReverser** [comment]
@dtolnay Also you said:

> I would still make the choice of leaving this as a known issue

but this issue is not "known" as in "mentioned in the docs for `serde(flatten)`", making it really hard to debug if you don't already know what you're looking for...

**Comment by clouds56** [comment]
I think a important thing here is that we lost struct name when using `serialize_map` instead of `serialize_struct`. is it possible to add a struct-like map to serializer
```rust
trait Serializer {
  // ...
  fn serialize_struct_map(
    self,
    name: &'static str,
    len: usize
  ) -> Result<Self::SerializeMap, Self::Error> {
    self.serialize_map(Some(len))
  }
}
trait Deserializer {
  // ...
  fn deserialize_struct_map<V>(
    self,
    name: &'static str,
    fields: &'static [&'static str],
    visitor: V
  ) -> Result<V::Value, Self::Error> {
    self.deserialize_map()
  }
}
```
which takes parameters like a struct, while returns a value like map.
Ideally the `serialize_struct_map` should return `Self::SerializeStructMap`, but for backward compatibility, it just returns `SerializeMap`.

Now https://github.com/ron-rs/ron/issues/115 is blocking on this. With this information, they could tell the different between "map because of flatten" and "map because of container", and land fix to handle with `flatten`
