### ISSUE TITLE
Unknown serde variant attribute `flatten`

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#1356]
Moved from https://github.com/serde-rs/serde/issues/119:

---

@philippludwig is using Serde 1.0.71 and receiving the following error.

```console
error: unknown serde variant attribute `flatten`
```

```rust
#[derive(Debug, Clone, Serialize, Deserialize)]
struct BuoyStation {
    #[serde(rename = "id")]
    station_id: String,

    owner: String, 

    #[serde(rename = "pgm")]
    program: String,

    #[serde(rename = "type")]
    buoy_type: BuoyType,

    #[serde(rename = "met")]
    active: bool,

    currents: bool,

    #[serde(rename = "waterquality")]
    water_quality: bool,

    dart: bool,

    #[serde(flatten)]
    location: Location,
}
```

**Comment by dtolnay** [comment]
Your code seems to compile as written. [Playground](https://play.rust-lang.org/?gist=52d45a0f929819be37960e9aa122d9de&version=stable&mode=debug&edition=2015)

Please try minimizing your code to the smallest possible self-contained snippet of code that reproduces your issue. If that isn't sufficient to figure out how to solve the issue, please share a way for me to reproduce what you are seeing and I can take a look. Thanks!

**Comment by mpiannucci** [comment]
Yeah its strange the exact code I am using is fine in the playground but fails no matter what I do with that exact error locally. I will have to dig a little more and hopefully find more detail to post.

**Comment by dtolnay** [comment]
Interesting. I will close the issue for now because there isn't anything actionable for me to look into, and you can let us know when you have minimized the issue in a reproducible way and you believe it needs to be addressed by code changes in Serde.

**Comment by mpiannucci** [comment]
I found the issue btw. I use cbindgen in my project and that is hard coded to serde_derive version 1.0.21 which was messing everything up. Without that dependency everything is fine.

**Comment by mareq** [comment]
Had a slightly different error, but this thread came out on top of google search for the error message, so adding my solution in case it helps someone:
For `#[serde(flatten)]` I have been getting ``error: cannot find attribute `serde` in this scope``. Turned out to be quite stupid problem of me not having `#[derive(Deserialize, Serialize)]` on my struct.

**Comment by dzdrav** [comment]
I stumbled upon the same error and it was due to something else, so contributing here for future googlers:

[Minimal example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c87da416e353f9729a67471138631e5b)
```rust
use serde::{Serialize, Deserialize};

#[derive(Debug, Serialize, Deserialize)]
enum Bla {
    #[serde(flatten)]
    Wrapped(String),
}

fn main() {}
```

fails with 
```rust
Compiling playground v0.0.1 (/playground)
error: unknown serde variant attribute `flatten`
 --> src/main.rs:5:13
  |
5 |     #[serde(flatten)]
  |             ^^^^^^^

error: could not compile `playground` due to previous error

```

After some research, although it's not stated explicitly in [the docs](https://serde.rs/field-attrs.html), I figured it wasn't applicable to an enum variant because [flatten](https://serde.rs/attr-flatten.html) 
>inlines keys from a field into the parent struct
>It is supported only within structs that have named fields, and the field to which it is applied must be a struct or map type"

So no enums (with associated values)
