### ISSUE TITLE
Set up CI build on Emscripten target

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#1366]
@koute do you know of any existing projects that test every commit on Emscripten? I would have liked to catch #1365 in CI. Is it as simple as just passing a `--target` to Cargo? Does that only let us test cross-compilation or is there a way to run our test suite as well?

**Comment by koute** [comment]
> @koute do you know of any existing projects that test every commit on Emscripten?

Yes! My [stdweb](https://github.com/koute/stdweb) does. (: In fact, this is how I caught this - suddenly my builds on stable started failing, and after more thorough investigation the culprit was the newest version of `serde_json` which switched to `ryu`.

> Is it as simple as just passing a --target to Cargo? Does that only let us test cross-compilation or is there a way to run our test suite as well?

Mostly, yes, however you need to manually install Emscripten (`rustup` doesn't install it for you) and manually run the test file yourself (or set a runner in `.cargo/config`). I don't know if that's still the case though, but there was also a bug where after a fresh installation of Emscripten you had to "warm" it up (basically the first compilation after installing Emscripten produces no artifacts but no error is generated).

You can either do it manually, or you can use my [cargo-web](https://github.com/koute/cargo-web) to automate it. It will automatically install the target through `rustup`, download Emscripten for you and work around the post install bug.

Basically, you can run this on Travis to install a precompiled binary of `cargo-web`:

```
CARGO_WEB_RELEASE=$(curl -L -s -H 'Accept: application/json' https://github.com/koute/cargo-web/releases/latest)
CARGO_WEB_VERSION=$(echo $CARGO_WEB_RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')
CARGO_WEB_URL="https://github.com/koute/cargo-web/releases/download/$CARGO_WEB_VERSION/cargo-web-x86_64-unknown-linux-gnu.gz"

echo "Downloading cargo-web from: $CARGO_WEB_URL"
curl -L $CARGO_WEB_URL | gzip -d > cargo-web
chmod +x cargo-web

mkdir -p ~/.cargo/bin
mv cargo-web ~/.cargo/bin
```

And then simply:

```
# Install Node.js
nvm install 9

# Run the tests.
cargo web test --target=asmjs-unknown-emscripten --nodejs
cargo web test --target=wasm32-unknown-emscripten --nodejs
```

(By default it runs the tests in a headless Chromium, but that's not necessary for projects which aren't strictly Web-related so `--nodejs` will make it run through Node.js.)

**Comment by dtolnay** [comment]
Amazing! Thanks, we'll get this set up and stop breaking your builds.

**Comment by dtolnay** [comment]
I couldn't get asmjs working because of

```console
error[E0463]: can't find crate for `proc_macro`
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.16/src/lib.rs:53:1
   |
53 | extern crate proc_macro;
   | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
```

but I added a wasm32-unknown-emscripten builder in #1373.

**Comment by koute** [comment]
@dtolnay It cannot find the `proc_macro` crate on the `asmjs-unknown-emscripten` as `proc_macro` seems to not be shipped by Rust for that target. (Which does make sense.)

If you remove `proc-macro2 = "0.4"` from the `[dev-dependencies]` of `serde_test_suite` then the `asmjs-unknown-unknown` will work. (Although you'd still need to extend the `#[cfg]`s in `tests/test_de.rs` `tests/test_ser.rs` and `tests/test_value.rs` to also handle `asmjs`, as they currently only match `wasm32`.)

**Comment by dtolnay** [comment]
Thanks, that worked!
