### ISSUE TITLE
Failed to build in nightly

### ISSUE THREAD

**Issue by amentis** [serde-rs/serde#1370]
using cargo 1.29.0-nightly, for serde v1.0.75 i cannot compile serde_derive same version because of error[E0599]: no method named `extend` found for type `&mut proc_macro::TokenStream` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.15/src/unstable.rs:170:21
    |
170 |                 tts.extend(
    |                     ^^^^^^
error[E0599]: no method named `extend` found for type `&mut proc_macro::TokenStream` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.15/src/unstable.rs:185:21
    |
185 |                 tts.extend(streams.into_iter().map(|stream| stream.unwrap_nightly()))
    |                     ^^^^^^

**Comment by dtolnay** [comment]
Thanks for the report. I am closing because Serde does not support old nightlies. The most recent nightly is 1.30.0-nightly from 2018-08-30, and should work. You are using 1.29.0-nightly which is not the most recent nightly. Generally "nightly" means that you are expected to upgrade the compiler "every night".
