### ISSUE TITLE
Avoid memory allocation when deserializing internally tagged enum

### ISSUE THREAD

**Issue by 1tgr** [serde-rs/serde#1407]
Currently deserialization of internally tagged enums goes via `TaggedContentVisitor` which grabs the tag field and put the rest of the content in a `Vec`: https://github.com/serde-rs/serde/blob/2a4b8ce42dad68a0ff1e26fb6bde502cfc20a122/serde/src/private/de.rs#L888-L916

I have a large volume of JSON data where the tag field (a string called `"type"`) is guaranteed to arrive at the start of the message. Could my deserializer take advantage of this and avoid the allocation of the rest of the content after it sees `type`?

**Comment by 1tgr** [comment]
I have a workaround, which is to deserialise a struct containing every field, and manually map to the correct subset based on the type.

I would like to attempt the change in serde to remove the allocation however.

**Comment by dtolnay** [comment]
Sounds good, I would be willing to consider such a PR. Please require the enum to opt into it however. Otherwise we would be emitting twice as much machine code for every internally tagged impl which affects compile time and binary size. Something like:

```rust
#[derive(Deserialize)]
#[serde(tag = "type", require_tag_first)]
enum E {
    /* ... */
}
```

**Comment by dtolnay** [comment]
Closing because, if possible, I would prefer for this optimized derive to be provided by a different crate. I don't think it is the right tradeoff to do the optimization by default in serde_derive because it would require generating so much more code, and I don't think the requirement for this to be optimized is common enough to justify an attribute to opt into the optimization.
