### ISSUE TITLE
unknown serde field attribute `flatten`

### ISSUE THREAD

**Issue by MarkSwanson** [serde-rs/serde#1409]
Has the 'flatten' field attribute been removed?
I've tried to define extra as a HashMap and a serde_json::Map and I get the same error.

```
use serde_json::{Map, Value};
#[derive(Serialize, Deserialize, Debug)]
  pub struct TestStruct {
      pub a: i32,

      #[serde(flatten)]
      pub extra: Map<String, Value>,
  }
```
Thanks!

**Comment by hcpl** [comment]
Have you updated your `serde` and `serde_derive` dependencies? Because on playpen your code works fine:

- with `HashMap`: https://play.rust-lang.org/?gist=872b5a898b4b320542438d9e58bbd244&version=stable&mode=debug&edition=2015
- with `serde_json::Map`: https://play.rust-lang.org/?gist=090ff5ee76fb955091021d3a08d31291&version=stable&mode=debug&edition=2015.

**Comment by MarkSwanson** [comment]
Oh my! 'cargo update' fixed it! 
Thank you so much!
