### ISSUE TITLE
Default tag.

### ISSUE THREAD

**Issue by dpc** [serde-rs/serde#1410]
I hava an `enum` with internal `tag`. However, for brevity, it's important for me to skip the tag if it has a default value. It goes both ways - if the tag is missing during deserialization, it means that the default variant should be used.

This is quite easily doable with normal fields, but does not seem possible with `#[tag = somefieldname]`, since I would have to use `default` and `skip_serializing_if` on `somefieldname`, which doesn't exist.

**Comment by dtolnay** [comment]
This is not well supported now. It is possible to capture this behavior in a handwritten Serialize and Deserialize impl but would be a lot of code. I would be interested in suggestions for how to support this better.

**Comment by dpc** [comment]
Naively speaking: allow `default_tag` and `skip_serializing_tag_if` on `enum`, and then make them work the same as `default` and `skip_serializing_if` on a normal field. :)

**Comment by dpc** [comment]
Actually, maybe `default_tag` should be on a variant itself?

**Comment by dtolnay** [comment]
I am going to close this issue because I don't believe it is a sufficiently common use case to justify adding two new serde attributes. It should be possible to make this work with a handwritten Serialize and Deserialize impl. If you get it working, please link to the commit to help anyone else looking for this pattern in the future.
