### ISSUE TITLE
Revive XML support

### ISSUE THREAD

**Issue by punkstarman** [serde-rs/serde#1446]
Dear Serde maintainers,

I am interested in reviving XML support for Serde. I believe that XML will be around for some time still, despite the gradual adoption of other formats such as JSON, YAML and TOML.

Currently the `serde_xml` crate has been abandonned (https://github.com/serde-deprecated/xml), and 
@RReverser has expressed looking for a maintainer to take over `serde_xml_rs` (https://github.com/RReverser/serde-xml-rs/issues/65). I responded in the same issue that I was interested.

While waiting for a response, I have taken up exploring my own implementation (https://github.com/punkstarman/serde-xml), firstly to explore TDD practices in Rust, secondly to see if certain design choices could have been made better, thirdly to go a lot further in implementing serialization. I would be open to continuing the the repo I started, taking over `serde_xml_rs` and merging ideas, or other possibilities.

What are your thoughts?
What could be the next steps?

**Comment by dtolnay** [comment]
Sounds good. Data format development happens in their own projects so permissions will need to be sorted out with whichever repo you end up using.

I would recommend less focus on roundtrip (as seen in your [*src/tests/round_trip.rs*](https://github.com/punkstarman/serde-xml/blob/ae836b0a5d09d21fe87b891ff4c106d6156120e7/src/tests/round_trip.rs)) because that tends not to be what people care about with XML in my experience. Roundtrip is useless if the XML format is predetermined by some other service. I would recommend collecting a diverse set of samples of real XML from real projects and making sure you can deserialize those samples into Rust data structures and generate those samples exactly from Rust data structures.

**Comment by punkstarman** [comment]
Thanks @dtolnay for the advice.

RReverser has added me as a contributor to `serde_xml_rs`. I'll start by jumping onto that, merging a few PRs and seeing what insights I can contribute there.

**Comment by dtolnay** [comment]
Okay!
