### ISSUE TITLE
Add capability to format numbers while serializing

### ISSUE THREAD

**Issue by lucatrv** [serde-rs/serde#1462]
I'm trying to serialize numbers to JSON in scientific format. The following example shows that numbers formatted with `format_args!` are serialized as strings, which is not what I am trying to achieve (scientific notation is supported by JSON: http://www.json.org).

```rust
use serde::ser::{Serialize, SerializeSeq, Serializer};

struct MyType(Vec<f64>);

impl<'a> Serialize for MyType {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut seq = serializer.serialize_seq(Some(self.0.len()))?;
        for element in &self.0 {
            seq.serialize_element(&format_args!("{:.5e}", element))?;
        }
        seq.end()
    }
}

fn main() {
    let x = MyType(vec![1., 2., 3.]);
    println!("JSON:");
    println!("{}", serde_json::to_string(&x).unwrap());
    println!("CSV:");
    let mut wtr = csv::Writer::from_writer(std::io::stdout());
    wtr.serialize(&x).unwrap();
    wtr.flush().unwrap();
}
```

The CSV example apparently works, but only because strings are saved without literal `"`.

To achieve this, as a minimum there should be a way to instruct the `serialize` method not to add `"` characters. Even better, there could be a `serialize_fmt` method which accepts a format string and applies it behind the scenes.

Please find a discussion on this topic here:
https://users.rust-lang.org/t/please-help-with-generic-types-serde-and-formatting/24420

**Comment by dtolnay** [comment]
The Serialize impl has no say in how data is formatted, only how data is hierarchically structured. Formatting is entirely up to the Serializer. In this case you'll need to use [`serde_json::Serializer::with_formatter`](https://docs.rs/serde_json/1.0/serde_json/struct.Serializer.html#method.with_formatter) to build a json Serializer in which you provide your own Formatter impl that prints numbers in the way that you decide.

**Comment by dtolnay** [comment]
I am closing this because it is not a goal of Serde to let a Serialize impl insert arbitrary characters into serialized output. For example your fmt::Arguments wouldn't make much sense stuck into a Bincode or CBOR binary output stream; the result would be syntactically invalid CBOR. Additionally, there is no restriction that data formats need to produce bytes at all. Some serializers like [`serde_json::to_value`](https://docs.rs/serde_json/1.0/serde_json/fn.to_value.html) produce a tree data structure rather than bytes as output. Some serializers produce only side effects and no output at all, i.e. the output is `()`. In those cases inserting bytes into the output isn't something we can let a Serialize impl do.

**Comment by lucatrv** [comment]
I see. Can you please let me know if [dcarosone's suggestion](https://users.rust-lang.org/t/please-help-with-generic-types-serde-and-formatting/24420/8) is feasible or not? Thanks in advance.
