### ISSUE TITLE
Deriving Deserialize with `deny_unknown_fields` and `flatten` generates code that Clippy warns about

### ISSUE THREAD

**Issue by luckysori** [serde-rs/serde#1491]
This code

```rust
#[macro_use]
extern crate serde_derive; // 1.0.88

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Foo {
    #[serde(flatten)]
    bar: Bar,
}

#[derive(Deserialize)]
struct Bar {
    a: String,
}
```

generates code which Clippy warns about:

```
warning: redundant closure found
 --> src/lib.rs:4:10
  |
4 | #[derive(Deserialize)]
  |          ^^^^^^^^^^^
  |
  = note: #[warn(clippy::redundant_closure)] on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure
```
[Rust Playground](https://play.integer32.com/?version=stable&mode=debug&edition=2018&gist=9b1f7dae7b42c895db3575aab53440ce).

**Comment by dtolnay** [comment]
Thanks! I would accept a PR to fix this.

**Comment by thomaseizinger** [comment]
So I tried to look into this and it turns out that there is actually already a test that would reproduce this.

However, the clippy job is set to "allow_failure" on travis and therefore doesn't run :sweat_smile: 

That is why this is issue was unnoticed. The fix is easy, should I try to activate the clippy job as part of the PR or should I leave it untested?
