### ISSUE TITLE
How to cross-compling serde?

### ISSUE THREAD

**Issue by BaoshanPang** [serde-rs/serde#1532]
I get these errors when trying to build it with command "cargo build --target=arm-unknown-linux-gnueabi": 

$ cargo build --target=arm-unknown-linux-gnueabi
   Compiling proc-macro2 v0.4.30
   Compiling unicode-xid v0.1.0
   Compiling syn v0.15.34
   Compiling ryu v0.2.8
   Compiling serde v1.0.91
error[E0463]: can't find crate for `std`
error[E0463]: can't find crate for `std`
error[E0463]: can't find crate for `std`
error[E0463]: can't find crate for `core`
error[E0463]: can't find crate for `std`
error: aborting due to previous error
error: aborting due to previous error
error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
For more information about this error, try `rustc --explain E0463`.
For more information about this error, try `rustc --explain E0463`.
error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `proc-macro2`.
warning: build failed, waiting for other jobs to finish...

Thanks,
Baoshan

**Comment by dtolnay** [comment]
Are you able to cross compile crates other than serde?

**Comment by BaoshanPang** [comment]
I am able to cross compile the crate tst (https://crates.io/crates/tst).

**Comment by dtolnay** [comment]
I am closing the issue because I am not going to have a chance to debug this with you and it does not look like anything specific to serde based upon the output you have shown. Since you have at least one crate that you can cross compile and at least one that you can't, I would recommend minimizing down to find the smallest possible repro code that doesn't cross compile. Once you have the minimal repro it should be clear what single thing is causing the failure.
