### ISSUE TITLE
[docs] which dependency / features do I need to manually implement Serialize / Deserialize

### ISSUE THREAD

**Issue by gnzlbg** [serde-rs/serde#1534]
I need to manually implement Serialize / Deserialize for a data-structure. I landed here: https://serde.rs/custom-serialization.html but nowhere does it there mention which crate and which features are the minimum ones for me to do that.

**Comment by dtolnay** [comment]
The page does provide links to the Serialize and Deserialize trait in the rustdoc of the serde crate, so the crate is clear. If there were features involved, they would be called out in the rustdoc and maybe also the page you linked. I don't find it necessary to mention "you don't need to enable any features to use this" on the page because I have not seen this be a common source of confusion.

To be clear the minimum requirement would be:

```toml
serde = { version = "1.0.0", default-features = false }
```

**Comment by gnzlbg** [comment]
I guess I was hoping for a way to just get the traits, without impls for all standard types, etc.
