### ISSUE TITLE
Erroneous "Default" bound when using `#[serde(default)]` in a generic context

### ISSUE THREAD

**Issue by Diggsey** [serde-rs/serde#1541]
I would expect these two examples to be exactly the same:

```rust
#[derive(Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize)]
pub struct Tagged<T> {
    #[serde(default)]
    pub v: Option<T>,
}
```

```rust
#[derive(Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize)]
pub struct Tagged<T> {
    #[serde(default = "Default::default")]
    pub v: Option<T>,
}
```

But the former only implements `Deserialize` when `T: Default`.

**Comment by AGausmann** [comment]
I believe this is part of a bigger, more general problem regarding generics and derives (rust-lang/rust#26925). The compiler plugins aren't given enough information to determine the right bounds to apply in these scenarios. For example, `#[derive(Default)] struct Wrapper<T>(Option<T>)` produces an implementation with a similar problem, it adds a bound `T: Default`

**Comment by dtolnay** [comment]
Yeah, this is https://github.com/rust-lang/rust/issues/26925. The workaround I would recommend is a `serde(bound(deserialize = ""))` attribute, which can go either on the field if there are other fields containing generic parameters for which we don't want to override the bounds, or on the struct otherwise.

```rust
#[derive(Deserialize)]
#[serde(bound(deserialize = "T: Deserialize<'de>"))]
pub struct Struct<T> {
    #[serde(default)]
    pub v: TypeWithDefault<T>,
}

// unbounded T on the Default impl
// impl<T> Default for TypeWithDefault<T>
```

**Comment by Diggsey** [comment]
@dtolnay This is not the same. Note: in both of my examples, the attribute is on the field, *not* on the struct, so the struct bounds should have no effect. In comparison, the issue you referred to is about the bounds on the struct itself.

There's no reason that the first example couldn't expand to the exact same code as the second example.

**Comment by dtolnay** [comment]
> In both of my examples, the attribute is on the field, *not* on the struct, so the struct bounds should have no effect.

None of the code snippets in this issue have trait bounds on a struct definition; I don't follow what you mean by "struct bounds" or why struct bounds should have no effect. Various code snippets have have trait bounds on a derived trait `impl`. Those bounds are inferred by derive macros based on field types and attributes.

**Comment by Diggsey** [comment]
> None of the code snippets in this issue have trait bounds on a struct definition

Let me ask the question a different way: why is `#[serde(default)]` not equivalent to `#[serde(default = "Default::default")]`? The issue you linked to is an issue with rust itself, and yet `#[serde(default = "Default::default")]` works fine, which implies this is an issue with serde instead.

**Comment by dtolnay** [comment]
> why is `#[serde(default)]` not equivalent to `#[serde(default = "...")]`?

The first one requires serde to instantiate the std::default::Default impl for the field's type, so it is reasonable to attempt to ensure a std::default::Default impl is available via bounding the impl's relevant generics. The second involves calling some arbitrary function which the user provides, so it would be reasonable to have the user also provide whatever bounds required by it, and it would not be a good idea to augment those with additional std::default::Default bounds since that trait is likely unrelated to the user's custom defaulting behavior.

https://github.com/rust-lang/rust/issues/26925 goes into more detail on why this approach to trait bounds is followed by *all* derive macros, whether distributed in the standard library or not.
