### ISSUE TITLE
cargo check fails

### ISSUE THREAD

**Issue by uggwar** [serde-rs/serde#1548]
Running cargo check on the first example in the documentation fails, but cargo build --release works like charm.

[cargo_check_serde_output.txt](https://github.com/serde-rs/serde/files/3260705/cargo_check_serde_output.txt)

**Comment by uggwar** [comment]
% rustc -V
rustc 1.35.0 (3c235d560 2019-05-20)

**Comment by uggwar** [comment]
% cargo +nightly -V
cargo 1.37.0-nightly (545f35425 2019-05-23)

% cargo +nightly check
   Compiling proc-macro2 v0.4.30
   Compiling unicode-xid v0.1.0
   Compiling syn v0.15.34
   Compiling ryu v0.2.8
   Compiling serde v1.0.92
    Checking itoa v0.4.4
   Compiling quote v0.6.12
   Compiling serde_derive v1.0.92
    Checking serde_json v1.0.39
    Checking lompe v0.1.0 (/home/christer/tmp/lompe)
    Finished dev [unoptimized + debuginfo] target(s) in 9.42s

**Comment by dtolnay** [comment]
Thanks! I am closing the issue because this doesn't look like something that would be fixed in Serde. It looks more like a Cargo issue. Could you report it in rust-lang/cargo with repro steps and the other information they ask for in Cargo's issue template? Take a look first whether anything similar has already been filed.

**Comment by uggwar** [comment]
Sure! Will do. :-)
