### ISSUE TITLE
The questions

### ISSUE THREAD

**Issue by GildedHonour** [serde-rs/serde#157]
This library is nothing but garbage which requires tremendous amount of effort not only to set it up but also to use afterwards.

1) What's OUT_DIR here? Why isn't it explained anywhere?

include!(concat!(env!("OUT_DIR"), "/main.rs"));

2) "Stable Rust is a little more complicated" -> I wouldn't say a little given that it's already complicated enough.

3) What's "src/main.rs.IN"? Why does it have the same content as main.rs?

4) "While this works well with Stable Rust, be aware that the error locations currently are reported in the generated file instead of in the source file. " -> of course.

5) Why does it have so many dependencies?

**Comment by Byron** [comment]
Starting an issue with
> This library is nothing but garbage
is disrespectful towards the authors of this crate, and I wonder how you would think this incentivizes anyone to provide support for you.

Usually I am the first one to plead guilty when it comes to writing these kinds of comments in initial rage, but by now I usually manage to save the draft, and revisit it next day to change a sentence or two.

As the Rust community really likes to be good to each other, I truly hope you find the time to revisit your text and change it to something less offensive. Maybe even given it a positive spin by making suggestions on how to make serde usage more convenient and user-friendly ? After all, your experience might be shared by others, and we really, really want to make it better.

**Comment by GildedHonour** [comment]
@Byron , I've tried to get the hang of it a few times and it's never panned out. If it's not one thing it's another.
Suggestion - make it more like the default Rust json library rustc_serialize.

**Comment by erickt** [comment]
@Byron: Thanks for the support.

@GildedHonour: Please try to remain civil, and just politely ask for help. I'm here or almost always on #rust. The serde macros do some very complicated things in order to do things in stable Rust, which has absolutely no support for compiler plugins. json and rustc_serialize (which I also wrote) cheat because they're actually built into the compiler. If you want ease of use, use nightly and `serde_macros`, which gives you pretty much the same user experience as json and rustc_serialize. Someday we'll get official support for plugins, and we can get rid of the [build scripts](http://doc.crates.io/build-script.html).
