### ISSUE TITLE
Bumping minor version while bumping a major version dependency

### ISSUE THREAD

**Issue by elichai** [serde-rs/serde#1602]
Hi,
In the last version of serde-derive (1.0.99) you bumped all dependencies a major version (syn,quote and proc-macro2) which now breaks compilers older than 1.31.

I don't want to get into the compiler versions - breaking changes again, but we would appreciate a major version bump breaking support with some compilers (which the syn,quote,proc-macro2 actually did nicely)
Right now this sadly breaks our code which requires to run on older compiler versions

**Comment by apoelstra** [comment]
In general, bumping a major version dependency is not a big deal if no types from that dep are exported.

The compiler version bump looks like it was intended to be caught by CI -- see https://travis-ci.org/serde-rs/serde/builds/572886513 -- but it looks like it wasn't sufficient in this case.

**Comment by elichai** [comment]
Hard to see from the phone but it seems like the old rust versions in the CI don't compile serde-derive

**Comment by oli-obk** [comment]
This was a known minimum required rustc version bump. When bumping crates.io dependencies it is not uncommon that the compiler version may also require a bump. You should use Cargo.lock and no unrestricted updates if you have hard requirements on compiler versions.

Bumping the compiler version dependency by a minor version does not require a major version bump as per semver, the same as bumping a crate dependency by a minor version does not require a major version bump

**Comment by dtolnay** [comment]
I've stayed out of the minimum supported compiler version discussions for a while but I think I am ready to come down on the side of this being something that tools need to be responsible for handling better. Those people whose use cases depend on supporting years-old compilers could put their effort to most productive use by driving proposals like https://github.com/rust-lang/rfcs/pull/2495 (not just commenting that someone should do the work, but really doing the work to prototype the right version resolution logic in Cargo and proposing concrete semantics) -- rather than debating with individual maintainers to take on more support burden.

It's been pointed out to rust-bitcoin folks that Serde doesn't have the policy that you assume, most recently in https://github.com/Stebalien/tempfile/issues/100#issuecomment-518321020 but also elsewhere iirc.

As a widely used crate we do prioritize minimizing disruption, which means for example it probably wouldn't fly if we changed compiler requirements every 6 weeks. But once every few years dropping old compilers (while retaining support for the last several stable releases) is definitely within reason. If for some use cases this is too disruptive, they remain free to decide whether not using Serde would be a better experience for what they need.

I would note that for all the attention to version support in rust-bitcoin, there are many ways that you could be doing better.

- The fix linked to this issue from https://github.com/rust-bitcoin/rust-bitcoin/pull/316 isn't a fix because the crate still doesn't build on old compilers. Try it yourself:

    ```console
    $ cargo new repro
    $ echo 'bitcoin = { version = "0.19", features = ["use-serde"] }' >> Cargo.toml
    $ cargo +1.25.0 build
    ```

    I am curious how long it would have taken anyone downstream to notice. :wink: 

- Dropping support for old versions of dependencies in a nonbreaking release is common practice and you do it too. Bitcoin 0.19.1 dropped support for old Serde versions. If someone had the following working project, it would be broken not by serde's patch but by your patch:

    ```toml
    [package]
    name = "downstream"
    version = "0.0.0"

    [dependencies]
    bitcoin = { version = "0.19", features = ["use-serde"] }
    serde = "=1.0.90"
    ```

    This compiles with bitcoin 0.19.0 but is broken by 0.19.1.

- The serde crate is still supporting back to rustc 1.13 for now, so the only reason bitcoin broke was because it has listed dependencies that you don't use. Bitcoin enables the "derive" feature on its serde dependency but never uses derive except in tests. That means downstream code is building 5 extra dependencies for no reason and `cargo +1.22.0 build --features use-serde` would never have been affected without it.

- I need you to acknowledge that "downstream code broke, therefore it is a breaking change" is **not** a useful definition of a breaking change. I know it seems obvious and intuitive, like @apoelstra wrote in https://github.com/Stebalien/tempfile/issues/100#issuecomment-518282361:

    > I'm really trying to understand the logic behind this statement but I cannot. How is breaking compilation *not* an API-breaking change?

    > Everything in the rust-bitcoin ecosystem considers it a breaking change to break compilation.

    I can try to help understand the logic. I know that it's appealing to define things in intuitive self-evident ways, but the whole community is better off if we define things in *the most useful way* instead. Defining a breaking change as something that breaks any downstream code is a thoroughly useless definition because that makes nearly every possible API change a breaking change. For us as a widely used library, and again thinking back to minimizing disruption, that just isn't a sensible or useful option.

    As a concrete demonstration, let's leave aside bitcoin's use-serde feature and look at what else is in bitcoin 0.19.1. The following project builds fine with 0.19.0 but is broken by 0.19.1.

    ```rust
    extern crate bitcoin;

    mod m {
        pub mod bech32 {}
    }

    use m::*;
    use bitcoin::*;
    use self::bech32;
    ```

---

I guess my recommendation would be to find a way to contribute to the tooling you use so that it fits your needs, or use a different serialization library, or use a different language. I'm not interested in getting into a longer discussion than this because it's already a well explored topic and I think we are doing the right thing. I'll let one of the commenters from rust-bitcoin have the last word if they want, but after that I plan to lock the issue.

**Comment by est31** [comment]
> doing the work to prototype the right version resolution logic in Cargo and proposing concrete semantics

FYI making MSRV's influence version resolution should be quite easy from a technical standpoint. Cargo already has support for yanked crates. All that's needed is extending the logic to treat crate versions with older MSRV's as yanked which is as easy as adding a filter to an iterator chain. I have a prototype patch that reads MSRV info from a json file [here](https://github.com/est31/cargo/commit/6ce9b611903b9be85cc6ad76a8eea09f7767d22b) and uses it for resolution. The part that writes that json file is missing, it would probably be synced from the internet like the registry is, but creating it doesn't even need an MSRV RFC or anything, just enough computational power to try compiling various crates with various Rust versions. The initial version of the MSRV RFC would help though as then you could forego compilation of those crates.

If anyone is interested in collaboration on a project to extend this prototype into a MSRV respecting cargo fork like how xargo is an std building cargo fork, please ping me over IRC or in this thread (unless it's locked then ping me in some other MSRV related thread :p). The cool part is that if the cargo fork is used to edit Cargo.lock, the MSRV resolution graph will also apply to vanilla cargo, allowing users to compile the project with unforked Cargo as well.

**Comment by apoelstra** [comment]
Thanks for giving me an opportunity to reply.

> I've stayed out of the minimum supported compiler version discussions for a while but I think I am ready to come down on the side of this being something that tools need to be responsible for handling better. Those people whose use cases depend on supporting years-old compilers could put their effort to most productive use by driving proposals like [rust-lang/rfcs#2495](https://github.com/rust-lang/rfcs/pull/2495) (not just commenting that someone should do the work, but really doing the work to prototype the right version resolution logic in Cargo and proposing concrete semantics) -- rather than debating with individual maintainers to take on more support burden.
> 

I don't think this is a fair characterization. I'm asking maintainers to bump their major version numbers when they make changes that increase the MSRV; this is already expected behavior for other forms of breaking changes. (Or alternately, maintainers could not make such changes, which would be even less work than making them.)

> It's been pointed out to rust-bitcoin folks that Serde doesn't have the policy that you assume, most recently in [Stebalien/tempfile#100 (comment)](https://github.com/Stebalien/tempfile/issues/100#issuecomment-518321020) but also elsewhere iirc.
> 

Yes, but serde does have a rust 1.13+ badge on its site, is a very well-established crate which has never caused such breakage before (even to the point of supporting 1.13 and 1.14 even when those versions lack custom derive, without which serde is quite unergonomic).

> As a widely used crate we do prioritize minimizing disruption, which means for example it probably wouldn't fly if we changed compiler requirements every 6 weeks. But once every few years dropping old compilers (while retaining support for the last several stable releases) is definitely within reason. If for some use cases this is too disruptive, they remain free to decide whether not using Serde would be a better experience for what they need.
> 

serde is a *very* widely disseminated crate. Deciding "whether or not to use serde" is tantamount to deciding whether or not to use the entire crates.io ecosystem. It reflects badly on this ecosystem that library maintainers would be forced to make such a choice if they want to support compilers older than [undefined but apparently < 1 year].

Having said this, I understand that it's actually only serde-derive which is affected, which is a much easier situation to resolve even without pinning versions (e.g. pre-1.15 we used to just NIH this with our own macros, which were fragile but easier to use than the `include!` hacks that were otherwise recommended).

> I would note that for all the attention to version support in rust-bitcoin, there are many ways that you could be doing better.
> 
>     * The fix linked to this issue from [rust-bitcoin/rust-bitcoin#316](https://github.com/rust-bitcoin/rust-bitcoin/pull/316) isn't a fix because the crate still doesn't build on old compilers. Try it yourself:
>       ```
>       $ cargo new repro
>       $ cd repro
>       $ echo 'bitcoin = { version = "0.19", features = ["use-serde"] }' >> Cargo.toml
>       $ cargo +1.25.0 build
>       ```
>       
>       
>       I am curious how long it would have taken anyone downstream to notice. wink
> 

It took about 15 minutes for rust-elements to notice. I decided to wait until this issue was resolved to take further action there (we may yank 0.19.1; certainly we will have to publish a 0.19.2 with a proper fix ... and probably new minor versions of 0.18, 0.17, 0.16, etc). It would surprise me if any other crates noticed within a week or two, since this all happened within 24 hours of rust-bitcoin releasing a new major version with several dramatic API changes; and anyone who noticed the breakage in older versions would see the open issues and PRs about it.

>     * Dropping support for old versions of dependencies in a nonbreaking release is common practice and you do it too. Bitcoin 0.19.1 dropped support for old Serde versions. If someone had the following working project, it would be broken not by serde's patch but by your patch:
>       ```toml
>       [package]
>       name = "downstream"
>       version = "0.0.0"
>       
>       [dependencies]
>       bitcoin = { version = "0.19", features = ["use-serde"] }
>       serde = "=1.0.90"
>       ```
>       
>       
>       This compiles with bitcoin 0.19.0 but is broken by 0.19.1.
> 

I am aware that pinning versions causes breakage. It appears that pinning is the least-breaking change we can make though when one of our dependencies causes breakage. I was hoping when you said "we could be doing better" that you would provide some specific suggestions.

>     * The serde crate is still supporting back to rustc 1.13 for now, so the only reason bitcoin broke was because it has listed dependencies that you don't use. Bitcoin enables the "derive" feature on its serde dependency but never uses derive except in tests. That means downstream code is building 5 extra dependencies for no reason and `cargo +1.22.0 build --features use-serde` would never have been affected without it.
> 

Yes, we will simply remove the implicit `serde-derive` dependency. (Though https://github.com/rust-lang/cargo/issues/1796 makes this a bit frustrating as we will need to change our tests in order for our CI to pass; though I somewhat understand how architecturally difficult that bug is to fix.) 

>     * I need you to acknowledge that "downstream code broke, therefore it is a breaking change" is **not** a useful definition of a breaking change. I know it seems obvious and intuitive, like @apoelstra wrote in [Stebalien/tempfile#100 (comment)](https://github.com/Stebalien/tempfile/issues/100#issuecomment-518282361):
>       > I'm really trying to understand the logic behind this statement but I cannot. How is breaking compilation _not_ an API-breaking change?
>       
>       
>       > Everything in the rust-bitcoin ecosystem considers it a breaking change to break compilation.
>       
>       
>       I can try to help understand the logic. I know that it's appealing to define things in intuitive self-evident ways, but the whole community is better off if we define things in _the most useful way_ instead. Defining a breaking change as something that breaks any downstream code is a thoroughly useless definition because that makes nearly every possible API change a breaking change. For us as a widely used library, and again thinking back to minimizing disruption, that just isn't a sensible or useful option.

There are several API changes (e.g. adding new methods to a trait with default implementations; adding new functions; adding new methods to objects) which are not considered breaking changes even though they will break some code, because (a) in order for this to cause breakage the downstream crate needs to have done something specific and hopefully-unlikely, e.g. defining their own method using a trait where the name conflicts; (b) to fix the breakage is fairly straightforward and can be done downstream. (I appreciate that this is not explicitly the reason that these things are excluded, but I'm trying to give an indication of where I'm coming from as a user of the crates ecosystem, and why these other breaking-but-not-semver-breaking API changes don't bother me.)

But increasing the MSRV of a dependency which often appears many levels deep is neither of these. I appreciate you expanding on the logic, but I continue to think that a "useful" definition of breaking change would include MSRV bumps.

(As an aside, which I definitely don't want to get into here, it is increasingly difficult to engage with the rust toolchain/compiler/language community, since the move to the javascript-only Discourse for long-form discussion and the move to the javascript-only and no-local-logs Zulip for short-form discussion.)

>  I'll let one of the commenters from rust-bitcoin have the last word if they want, but after that I plan to lock the issue.

I think I've said all that I want to say.
