### ISSUE TITLE
Serialize type of a value

### ISSUE THREAD

**Issue by chenyan2002** [serde-rs/serde#1616]
Is there a way to serialize the type of a rust value? For example, given a value `None` of type `Option<i32>`, I want to serialize it to some encoding of `[Option<i32>][None]`. More generally, for enum types, when I get to `serialize_struct_variant` or `serialize_none`, I only know the type of the current enum value, not the type of the enum.

One way I can see is to use `proc_macro` to derive a trait for describing the type of enum. In the macro, I will need to inspect `syn::Type` of each `syn::Field`. This feels like re-implementing the `serde` framework for types. Is there an easier way?

**Comment by dtolnay** [comment]
Serde doesn't have this information, since we operate on values only, not types. You could try using something like [TypeInfo](https://github.com/dflemstr/type-info) or [Reflection](https://github.com/oooutlk/reflection) to determine the type, or write a new proc macro for it if neither of these exposes the information you need.

**Comment by chenyan2002** [comment]
Thanks! This is exactly what I need. Interestingly, there is also [https://github.com/srijs/rust-serde-schema](serde_schema) that does the same thing, but seems to be at early stage.
