### ISSUE TITLE
serde doesn't seem to use SemVer correctly

### ISSUE THREAD

**Issue by Kixunil** [serde-rs/serde#1632]
According to https://semver.org

```
Given a version number MAJOR.MINOR.PATCH, increment the:

    MAJOR version when you make incompatible API changes,
    MINOR version when you add functionality in a backwards compatible manner, and
    PATCH version when you make backwards compatible bug fixes.
```

Serde added new features since `1.0.0`, but `MINOR` is still `0`. My understanding is that a code written against `x.y.z` should work with `x.y.(z-1)` for all `z > 0` apart from the issues fixed in the specific releases.

Specifically `1.0.90` adds a new attribute `#[serde(crate = "...")]`, which is a backwards-compatible feature (doesn't break old code), but the crates using it won't work with `1.0.89`. Thus I think `MINOR` should be bumped.

**Comment by dtolnay** [comment]
This is true. We don't claim to use semver at all though so this is fine. ;)

**Comment by Kixunil** [comment]
Ah, OK, might be worth explicitly pointing out in README. :) Thank you!

**Comment by casey** [comment]
I ran into a small issue because serde doesn't follow semver's minor-release-for-new-features policy, and I wanted to share, since it's semi obscure, and might motivate the adoption of the policy for serde.

Debian requires that dependent crates be packaged independently. Since the Debian-packaged versions of crates might lag behind the latest version on crates.io, packagers benefit from being able to use older versions of dependencies, since that older version may already be packaged for Debian.

So one of the checks that I do for my crates is ensure that they actually build with the minimal compatible version declared in `Cargo.lock`. The easiest way to do this is with:

```sh
$ cargo +nightly generate-lockfile -Z minimal-versions
$ cargo test
```

A crate I'm working on that declares a dependency on `serde = "1"` failed to build, due to a dependency on the `flatten` attribute, which wasn't present in serde 1.0.

If serde followed semver, and we were up to, say, serde 1.2, I would have declared my dependency  to be on serde 1.2 to begin with, and the crate would have built with the minimal generated lockfile.

As it was I had to look at release notes to realize that new features are included in serde in patch releases, and then go through the patch releases to figure out which version I actually depended on.

Of course, there are definitely cases where following semver doesn't help for this, for example if your code hits a bug in a dependency, which is fixed in a patch release, and thus you depend on that patch release and above.

Anyways, I'm sure you have good reasons for not adopting this policy from semver, but I wanted to share.

Thanks for the great library, for me serde is a huge part of why rust is a pleasure to use!
