### ISSUE TITLE
Dynamically renaming struct fields

### ISSUE THREAD

**Issue by regar42** [serde-rs/serde#1686]
Hi,
I use an API that takes structs with custom fields. For example, I can send this:
```
{
    // Regular fields
    "id": 1,
    "name": "whatever",
     // Custom field with unique name
     "475b9389cad9377198d0fabb756cfd4c5faf2eb3": "whatever"
}
```

The API uses these fields to map data to user-defined fields, therefore the names of these custom fields depend on the context of the API call. For example, when developing, I may use different accounts, each one having its different custom fields set (the data associated to them is the same, it's just the sha identifying the fields that change).
I would therefore need to rename my struct fields when serializing, as with serde `rename`, but instead of using a literal, using a value computed at runtime.
For example I could serialize this struct:
```
struct Example {
  id: usize,
  name: String,
  #[serde(rename_with = "fn")]
  my_custom_field: String
}
```
and `my_custom_field` would be renamed to the correct custom field name (for example depending on whether I'm in prod or dev).
It seems this feature might be handy for similar cases I came across when looking for dynamic renaming. Do you think it could be integrated in serde or should I rather implement my own serializer?

**Comment by Ten0** [comment]
This would be the structure that has to be updated: https://github.com/serde-rs/serde/blob/d4d737de8d5a08104a7b4b0bc072715fe112af2e/serde_derive/src/internals/attr.rs#L136

Probably something like what is done with `skip_serializing_if` could be done.
The difficulty is these always return a `bool`, while in our case we'd probably want to support functions returning both `&str` (maybe dynamically generated through `lazy_static` or depending on the name) and `String`s (maybe dynamically generated based on the field name, maybe even through the content of the field that is being serialized, maybe based on static environment and could be cached)...

**Comment by H2CO3** [comment]
> The API uses these fields to map data to user-defined fields, therefore the names of these custom fields depend on the context of the API call.

That sounds exactly like a regulr `enum` to me, where every case has its own set of associated fields.

Alternatively, for a less type-safe solution, you can just `#[flatten]` a `HashMap<String, …>` into the top-level struct, depending on the structure of your type.

Dynamic renaming can *easily* become *very* confusing, and both listing the possible cases in an `enum` and clearly indicating the "anything goes" part by flattening a map are strictly better solutions.

**Comment by Ten0** [comment]
> That sounds exactly like a regular enum to me, where every case has its own set of associated fields

That's not exactly the same, for several reasons:
 - The api-names of the fields can different based on the environment (say, devlopment, production), but the names and types would be the same, so basically all the contents would the same, just the api-names are different. We wouldn't want to use the awful names when coding the rest of the code.
 - The information about which rename version has to be triggered is not meant to be stored in the sructure and then matched against (this is not optimal from a performance standpoint, though probably neglictable compared to the API call that comes right after, but also opens the representation of several structures in the same app that don't rename in the same way because they don't use the same variant, which is another type-safety guarantee that would be nice to have).
 - If the fields api-names are loaded dynamically (say, fetched from the API in a `lazy_static`), you can't use an enum.

> `#[flatten]` a `HashMap<String, …>`

Again, we need to fill and read from these structs at some point. This would make the interface awful.


Currently, we're actually using a dynamic translation by first serializing the struct to a `serde_json::Value`, then extracting the underlying `Map` and renaming the fields from there.

> Dynamic renaming can *easily* become *very* confusing

Absolutely, which is one of the reasons why I'd also want to avoid using an "anything goes" translation like this one through a `Map`, which offers little guarantee that you haven't forgotten to rename a field: they are written aside and there's no such thing as exhaustivity guarantee at compile time if you write it this way, you could make typos in the names of the fields you rename from, you could forget to rename one (actually a minority of them need renaming, but if the field name and the "whether it should be renamed" are too far apart, it's easy to miss one), etc...

Covering some of these issues through unit testing would be doeable (derive something else to extract all field names and make sure the rename wouldn't hit fields that don't exist), but I feel that having the compile-time guarantee from Serde would be safer (the whether to rename would be right above the field definition, so less risk to forget it), easier, and cleaner.

**Comment by dtolnay** [comment]
I would prefer not to build anything dedicated to this into serde_derive. But if someone wanted to put together a more fully featured derive macro as a separate library, I think that would be welcome.
