### ISSUE TITLE
Exposing numeric identifiers for struct types

### ISSUE THREAD

**Issue by djc** [serde-rs/serde#1697]
In my implementation of the AMQP 1.0 spec, I've run into some issues with how struct types are serialized. In AMQP 1.0, structs are serialized as "described types", which is basically:

- A null byte
- A descriptor, starting with a format code
- A "list" representing the object's fields

Descriptors have two forms: ASCII strings and u64. Any given type can thus have have both an integer and a string identifier. However, as far as I can tell, a `Serializer` (unlike a `Deserializer`) has no defined way to set a non-string identifier for a struct. The only options I see are:

- Generating custom `Serialize` impls; I think this would be a bit ugly because of the ordering. I'd then insert the serializer and serialize the fields as if it was a tuple.
- Smuggle both identifiers into the type name using `serde(rename)`, then parse that name to separate them again

Two potential avenues for making this easier:

- Introduce a `serde(id = )` meta key that would attach a numeric identifier apart from the string one. The problem here is that u64 is maybe not a generically useful type for this, and I'm guessing having `Serializer`-specific types also wouldn't generalize across `Serialize` impls.
- Introduce an alternative `serialize_struct_seed()` like method on `Serializer` that gets the type of the field as a generic argument similar to how `Deserializer` has it. This seems like it could enable a bunch more things and might be made backwards compatible (I think) if there was a default implementation that forwarded to the old-style `serialize_struct()` method.

I'm happy to do some implementation work if any of this would be acceptable.

**Comment by nickray** [comment]
Hey @djc I'm in the same boat. In the [FIDO2 CTAP2](https://fidoalliance.org/specs/fido-v2.0-ps-20190130/fido-client-to-authenticator-protocol-v2.0-ps-20190130.html#ctap2-canonical-cbor-encoding-form) protocol, a modified of CBOR is used, where the top-level struct of a message has integer indices instead of string keys, and to make it more fun, indices start at 1 instead of 0. 

I have quite a lot of types, an additional requirement is that some keys are optional: [typical example](https://github.com/nickray/usbd-ctaphid/blob/4018f51af8761dc171457a06fd8469963e0e7d42/src/types.rs#L253-L262).

The existing `serde_cbor` library implements integer indices at the [serializer](https://github.com/pyfisch/cbor/blob/16c3c1c76c6c79e94f7ac6c3b2a6bf8d07c09e9c/src/ser.rs#L601-L605) and [deserializer](https://github.com/pyfisch/cbor/blob/16c3c1c76c6c79e94f7ac6c3b2a6bf8d07c09e9c/src/de.rs#L988-L990) level, but has shown [unwilligness](https://github.com/pyfisch/cbor/pull/168) to add more flexibility.

Thinking from my use case's perspective, I have been imagining a `#[serde(index)]` container attribute (naming open to bikeshedding), that extends use of the [`FIELDS`](https://github.com/serde-rs/serde/blob/895eb2ba6c743cac9469af50da03210b6ea5b5cd/serde_derive/src/de.rs#L1608) in deserialization, somehow adds support for either just "start at one" `#[serde(index_from_one)]` or a general offset (something like `#[serde(index(offset = 1))]`, and then maps structs to maps in serialization/deserialization.

Would this kind of approach work for you too?

An alternative approach I'm exploring currently is to use `#[serde(into = "IntoType")]` and `#[serde(from = "FromType")]` with actual map types (in my specific case, perhaps with https://docs.rs/heapless/struct.LinearMap.html), generating the conversion traits with a macro, however I would prefer to avoid this type explosion, not least for efficiency reasons.

I have ~zero knowledge of proc-macros currently, but this seems like a good way to learn them! My plan is to start with an analogue of https://github.com/dtolnay/serde-repr (e.g., `serde-indexed`) that implements custom `Serialialize`/`Deserialize`, and depending on how that goes, try and come up with a container attribute instead.

Have you started any work on your approaches?

**Comment by nickray** [comment]
Update: I made a little proof of concept, https://github.com/nickray/serde-indexed.

**Comment by djc** [comment]
Can you paste examples of the generated impls somewhere?

**Comment by nickray** [comment]
You can run `cargo expand --test basics`, note this is still _very_ much WIP.

**Comment by dtolnay** [comment]
I think I would prefer not to build anything into serde for this, but it would be reasonable for a data format like this to ship with its own derive macro, whether deriving the Serialize trait, or a totally different trait, or a schema to augment the Serialize impl kind of like how a schema is used when serializing in https://github.com/flavray/avro-rs.
