### ISSUE TITLE
skip_deserializing_if macro

### ISSUE THREAD

**Issue by guskovd** [serde-rs/serde#1736]
I use skip_serializing_if to skip some fields in my struct. want to be able to conditional deserialize

**Comment by vallentin** [comment]
Unless I'm misunderstanding, then you could use `#[serde(default)]`.

Say you have a `Vec<String>` of `names`. You only want it serialized if it is not empty, then you could define it like this:

```rust
#[serde(skip_serializing_if = "Vec::is_empty")]
#[serde(default)]
names: Vec<String>
```

**Comment by dtolnay** [comment]
Please clarify if the suggestion above is not what you meant by conditionally deserializing.

**Comment by rwthompsonii** [comment]
I would like the ability to conditionally ignore deserialization if the type is not as expected.  Don't break the whole deserialization if I was given a string where a map was expected.

**Comment by jonasbb** [comment]
@rwthompsonii I think [`serde_with::DefaultOnError`](https://docs.rs/serde_with/1.5.0-alpha.2/serde_with/struct.DefaultOnError.html) solves this problem.

**Comment by vagola** [comment]
I have an untagged enum and I want to skip fields on deserialization

**Comment by kevlarr** [comment]
@jonasbb Correct me if I'm wrong, but the generalized "default on error" approach isn't necessarily as useful as a `skip_deserialize_if` macro would be.

For instance, Postgres has a lot of 'magic string' values basically representing enums. The `pg_catalog.pg_attribute.attidentity` column returns `'a'` if it's always generated, `'d'` if generated by default, and `''` if not an identity column (that's an empty string rather than null).

While I _could_ use a "default on error" approach, that would always give a default value if my code gets an unexpected string, not just an empty one, right? An attribute like `#[serde(skip_deserialize_if = "String::empty")]` attribute would give me greater control, since I could declaratively ignore empty strings (and let the default value of the field be `None` rather than `Some<MyEnum>`) and then my custom `impl Deserialize for MyEnum` could error out on non-empty but invalid strings.

**Comment by KalyanKadiyala** [comment]
> [@rwthompsonii](https://github.com/rwthompsonii) I think [`serde_with::DefaultOnError`](https://docs.rs/serde_with/1.5.0-alpha.2/serde_with/struct.DefaultOnError.html) solves this problem.

Suggested approach wouldn't work in cases where the objective is to ignore the entry in case of error, where collecting a default isn't the expected outcome. Consider the following example associated with CPU interrupts...

```
 "sum-interrupts": [
        {"cpu": "all", "intr": 456.81},
        {"cpu": "0", "intr": 52.71},
        {"cpu": "1", "intr": 30.31},
        {"cpu": "2", "intr": 40.72},
        {"cpu": "3", "intr": 25.53},
        {"cpu": "4", "intr": 45.30},
        {"cpu": "5", "intr": 26.81},
        {"cpu": "6", "intr": 41.71},
        {"cpu": "7", "intr": 24.12}
],
```
I'd like to map this to following Struct

`struct sumInterrupts{
    cpu: u8, 
    intr: f32
}`

by ignoring the first entry that'd error. 

Probably the skip_deserializing_if is a better choice! Any thoughts on this, as expressed in the above comment? For now, I can use an interim struct with key set to a String to ignore and collect key-value pairs of certain expected type. 

Thanks,
Kalyan
