### ISSUE TITLE
Serializing/Deserializing HashMap<Struct, f32> inside another Struct.

### ISSUE THREAD

**Issue by davideps** [serde-rs/serde#1757]
Hi folks,

I have this struct:

    #[derive(Debug, Serialize)]
    struct AreaStimulus {
        sense:  Sense,  //enum
        oid:    usize,    
        turn:   usize,    
        origin: Point,  // x and y struct
        val:   HashMap<Point, f32>
    }

If the HashMap were <String, f32> I would use this code to store it in sqlite:

    fn store_stimuli(conn: &mut Connection, path :&str, turn :usize, stimuli: &DashMap<usize, AreaStimulus>) -> Result<()> {
            let tx = conn.transaction()?;
            let sql = "INSERT INTO stimuli (path, turn, oid, sense, orig_turn, orig_x, orig_y, val)
                      VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)";
            let mut stmt = tx.prepare(sql)?;
            stimuli.iter().for_each(|stimulus| {
                let (oid, this_stimulus) = stimulus.pair();
                stmt.execute(rusqlite::params![
                path, turn as i64, *oid as i64,
                format!("{:?}",this_stimulus.sense), this_stimulus.turn as i64,
                this_stimulus.origin.x as i64, this_stimulus.origin.y as i64,
                serde_json::to_string(&this_stimulus.val).unwrap(),
            ]).unwrap();
            });
            drop(stmt);
            tx.commit()?;
            Ok(())
        }

I'm having trouble writing a serde serializer and deserializer for the HashMap<Point, f32> version. I think the code should look something like this:

     fn serialize_point_hashmap<S>(x: HashMap<Point, f32>, s:S) -> Result<S::Ok, S::Error> {
        where
        S: Serializer,
        {
            for (k, v) in x {
                s.serialize(format!("({},{})",{};", &k.x.to_string(), &k.y.to_string(), &v)?;
            }
        }
    }

I'm new to Rust. I'd appreciate some guidance. Thank you!

**Comment by rw** [comment]
@davideps Unfortunately, the provided explanation is not enough information to debug your issue. I attempted to infer your intentions and wrote a version of your code [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6176d7efb0dfdf7e541aab829ceec80f).

That code does not compile because f64 does not implement the traits required for insertion into a hash table: Eq and Hash.

This is a common roadblock when learning Rust. It turns out that floating point values have edge cases, like NaN and subnormals and infinities, that complicate what it means for two floats to be equal. So, the standard library does not make that choice for you.

Luckily, there are libraries available that implement the traits you need on floats. They wrap the floating point types to provide a total ordering.

As an example, here is a [re-implementation of your code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c4078d098b081df6f60daa84518c7aad) that I wrote using the ordered-float library. (Note that, for your use case, you'll want to use the ordered-float library with the "serde" feature to enable serialization and deserialization.)

Does that help?

**Comment by davideps** [comment]
Thanks Robert. I'm storing the AreaStimulus struct in sqlite using rusqlite. If the HashMap were <String, f32> then the code above stores the struct correctly, serializing the HashMap into a single TEXT field as JSON using serde. The other fields don't need serde. I had to cast some numeric fields to i64 because sqlite does not have an unsigned type like usize.

**The problem** is that I prefer the map to be HashMap<Point, f32> with Point being x and y (usize). I included some incomplete code for the serializer for this version of the HashMap. Ultimately, I would like to serialize the HashMap as CBOR and store it in a sqlite BLOB column. The other fields would remain human-readable as already implemented in store_stimuli() above.

**Comment by rw** [comment]
@davideps I don't understand, what prevents you from doing this?

> Ultimately, I would like to serialize the HashMap as CBOR and store it in a sqlite BLOB column.

**Comment by davideps** [comment]
Serde's built-in serializer for HashMap requires the key to be a String. I would like to use a Point struct as a key. That means, I need to write a custom serializer, something like this https://stackoverflow.com/questions/51276896/how-do-i-use-serde-to-serialize-a-hashmap-with-structs-as-keys-to-json except I want CBOR as the target format. Maybe I need to convert to serde's internal format and then the CBOR conversion has already been implemented here https://docs.rs/serde_cbor/0.11.1/serde_cbor/.

**Comment by dtolnay** [comment]
Hi @davideps, sorry that no one was able to provide more help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
