### ISSUE TITLE
Field attribute for combining `default` and `skip_serializing_if`

### ISSUE THREAD

**Issue by kaikalii** [serde-rs/serde#1782]
I like to make sure that the serialized versions of my data structures hold the minimum amount of data possible and that missing fields get set to sensible defaults during deserialization. In general, if a field is equal to some default value, I like to skip serializing it. I use this same default value as the default for deserializing. I find that the solution to this problem that makes the most sense using the currently available serde_derive attributes looks something like the following:
```rust
use serde_derive::{Serialize, Deserialize};

#[derive(Serialize, Deserialize)]
struct Foo {
    #[serde(default = "default_bar", skip_serializing_if = "is_default_bar")]
    bar: u32
}

fn default_bar() -> u32 {
    5
}

fn is_default_bar(bar: &u32) -> bool {
    bar == &default_bar()
}
```

This works perfectly fine, but it is cumbersome to have to create two other functions just for this purpose. It would be nice if I could do something like this:
```rust
use serde_derive::{Serialize, Deserialize};

#[derive(Serialize, Deserialize)]
struct Foo {
    #[serde(skip_default = 5)]
    bar: u32
}
```

Is this reasonable?

**Comment by ratijas** [comment]
This is totally reasonable, and I'd like that. But it assumes `Copy` types of given expressions.

Personally, I found this issue because I was looking for skipping defaults too. I'd start with something as specific as `#[serde(skip_serializing_if_default)]` which would check for equality with the type's `Default::default()` value. It would not be bounded to Copy, so should work on empty vectors, maps, strings etc.

**Comment by dtolnay** [comment]
I think this isn't a widespread enough use case that it would be worthwhile to build dedicated shorthand for this into serde_derive. However someone could provide a different `Deserialize` derive macro in a different crate which could be more fully featured and handle this case more concisely.
