### ISSUE TITLE
Deserialize from sequence or map

### ISSUE THREAD

**Issue by Plecra** [serde-rs/serde#1784]
How might I write a `Deserialize` implementation that allowed my type to be deserialized from a sequences of values or a map of values?
```rust
struct Values(Vec<T>);

assert_eq!(&serde_json::from_str::<Values>(r#"{ "foo": 89 }"#).0, [89]);
assert_eq!(&serde_json::from_str::<Values>(r#"[89]"#).0, [89]);
```

**Comment by agausmann** [comment]
You can do this purely with `derive` macros, using a remote type that tries both `Vec` and `HashMap`. This might have some additional overhead from the extra allocations, I'm not sure if the compiler can optimize that. You could also replace the `String` key with an [`IgnoredAny`](https://docs.rs/serde/1.0.106/serde/de/struct.IgnoredAny.html), or a [`RawValue`](https://docs.rs/serde_json/1.0.44/serde_json/value/struct.RawValue.html) if your data format has something like that, to explicitly prevent allocations there. Unfortunately, the trait bounds required by `HashMap` and other map types make that difficult.

[(playground)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=59b9cd7399e801c05c370dbf9ab5fa58)

```rust
use serde::{Serialize, Deserialize};
use std::collections::HashMap;

#[derive(Serialize, Deserialize)]
#[serde(from = "ValuesHelper<T>")]
struct Values<T>(Vec<T>);

#[derive(Deserialize)]
#[serde(untagged)]
enum ValuesHelper<T> {
    Seq(Vec<T>),
    Map(HashMap<String, T>),
}

impl<T> From<ValuesHelper<T>> for Values<T> {
    fn from(helper: ValuesHelper<T>) -> Values<T> {
        match helper {
            ValuesHelper::Seq(seq) => Values(seq),
            ValuesHelper::Map(map) => Values(map.into_iter().map(|(_k, v)| v).collect()),
        }
    }
}
```

You could also write the `Deserialize` impl manually and implement both `visit_map` and `visit_seq` on your [`Visitor`](https://docs.rs/serde/1.0.106/serde/de/trait.Visitor.html) so it will handle both cases. It'll be a lot easier to optimize, you're more free to use `IgnoredAny` there for your key type, and you can construct the `Vec` directly instead of making a map first.

**Comment by Plecra** [comment]
This is the best I could come up with

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=13dda92630402c84ee3df0e056221988

The problem is that it uses `deserialize_any`, so it cannot work with formats that aren't self describing. I still want to hint to the deserializer that I'm expecting a sequence, but `serde_json` raises an error if I call `deserialize_seq`.

What does the implementation of `untagged` do to handle this? I find it really hard to read through the `derive` macros code >.<

**Comment by Plecra** [comment]
Now that I think about it, I'm not sure why `serde_json` is emitting that error anyway - serde's model uses `Visitor`'s default implementations to create `invalid_type` errors, and it seems like `Deserializer`s *should* just treat the type they're called with as a hint.

Is there any specification for this? It'd be nice if serde could guarantee this, but it's probably a bit late for that :P

**Comment by agausmann** [comment]
> The problem is that it uses deserialize_any, so it cannot work with formats that aren't self describing.

Yes, this is probably the biggest problem with this kind of "dynamic" and untagged structure, it's only compatible with self-describing formats. If you want to store it in something like Bincode, you're going to have to have another `Serialize`/`Deserialize` impl that uses tagging to determine whether the data is an array or a map.

**Comment by agausmann** [comment]
> serde's model uses `Visitor`'s default implementations to create `invalid_type` errors, and it seems like `Deserializer`s _should_ just treat the type they're called with as a hint.

Yes, I'd consider it good practice for `Deserializer`s to be as lenient as possible and only use `deserialize_*` as hints, though it's not strictly required by the contract. I just ran into this in #1803 as well, I assumed that certain parts of the `serde_derive` internals would be more permissive/transparent than they actually are. It's definitely something that the community needs to discuss in depth more, and try to figure out when it's appropriate for `Deserializer`s to error. Personally I think deferring to the `Visitor` for these checks is the best option, but it'd be nice to get a maintainer's perspective on this

**Comment by agausmann** [comment]
dtolnay made a really good point in https://github.com/serde-rs/serde/issues/1803#issuecomment-625406210 about how more permissive `Deserializer` impls can make the binary sizes larger, it basically requires all of the visitor methods to be present in the resulting binary even if only a few are needed.
