### ISSUE TITLE
circular json?

### ISSUE THREAD

**Issue by GopherJ** [serde-rs/serde#1819]
stackoverflow when circular structure detected

**Comment by dtolnay** [comment]
Can you provide a compilable minimal program that reproduces this, preferably a https://play.rust-lang.org link?

**Comment by GopherJ** [comment]
@dtolnay https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5becf04a5ef64ff5cf1dfece0006afd9

**Comment by dtolnay** [comment]
Arc cycles are not something that Serde would handle (just like it wouldn't be something that Debug impls or Drop impls automatically deal with). The right behavior is highly application-specific.

Also make sure to write those Drop impls because the Arc cycle in that code will cause all the Nodes to be leaked.

**Comment by GopherJ** [comment]
@dtolnay  in my real application there is no circular because I removed them in code so leak should be fine. However if serde can handle circular json maybe I dont need this mechanism.
