### ISSUE TITLE
Deserializing to std::borrow::Cow<str> always allocates

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [serde-rs/serde#1852]
```rust
// [dependencies]
// serde_json = "1.0.41"
fn main() {
    let v = "hello";
    let s = serde_json::to_string(&v).unwrap();
    println!("{}", s);
    let v2: std::borrow::Cow<str> = serde_json::from_str(&s).unwrap();
    match v2 {
        std::borrow::Cow::Borrowed(..) => println!("borrowed"),
        std::borrow::Cow::Owned(..) => println!("owned"),
    }
}
```

### Expected result
```
"hello"
borrowed
```

Because string `hello` appears in the data as is, with no escaping or reader buffer boundaries.

### Actual result
```
"hello"
owned
```

**Comment by chpio** [comment]
Seem to work ok by putting the `Cow` in a newtype wrapper and adding the `borrow` attribute to the `Cow` field: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=9ba7a398755c35aa9ad24baa7c745371

**Comment by mqudsi** [comment]
Is [the demonstration from above](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=418dd6b98dfa62d43c4cc7fa8b7ea0d6) the only way to use `deserialize_with` to support both borrowed and owned deserialization?

I realized that I can ship a library w/ its standardized json format and struct definitions with `#[deserialize_with = ...]` annotated everywhere correctly, include tests that cover json deserialization using `serde_json::from_str()` that pass perfectly, then realize later that a simple `deserialize_with()` target that doesn't delegate work to a `Visitor` impl but rather just deserializes on the spot can end up failing every time if a consumer of the library tries to deserialize to the same struct using `serde_json::from_reader()` instead of `serde_json::from_string()`.

**Comment by Lucretiel** [comment]
Why would it fail? `from_reader` would use `visit_str` instead of `visit_borrowed_str`, so it should still work

**Comment by mqudsi** [comment]
That's only if you specifically implement and go through the `Deserialize` trait. As I mentioned, I was asking about the simpler/less boilerplate self-contained approach of attempting to decode directly in the function named as the `deserialize_with` target.

**Comment by dtolnay** [comment]
I think this is the intended behavior. For better or worse, there only gets to be 1 `Deserialize<'de>` trait impl for `Cow<'a, str>`. Either that impl has a `'de: 'a` bound, or it doesn't, and different common usage patterns need a `deserialize_with` and/or `borrow` attribute either way. I think the way this is currently implemented is the best tradeoff.

**Comment by fogti** [comment]
Can the other alternative be implemented, perhaps via a wrapper? has someone done so already? (similar to the `serde-bytes` stuff?; perhaps even put it into exactly that crate?)

**Comment by dtolnay** [comment]
Yeah, if it would be helpful someone could implement `BorrowCow` that mirrors the API of `Cow` but with the opposite lifetime bound for the Deserialize impl.
