### ISSUE TITLE
Deserializing flattened Option field produces None instead of errors

### ISSUE THREAD

**Issue by nooberfsh** [serde-rs/serde#1880]
code:
```rust
use serde::{Serialize, Deserialize};

#[derive(Debug, Serialize, Deserialize)]
struct Res {
    r: i32,
    #[serde(flatten)]
    d: Option<Data>,
}

#[derive(Debug, Serialize, Deserialize)]
struct Data {
    b: bool,    // expected type is bool
}

fn main() {
    let s = r#"{"r":1, "b": "1"}"#;     //  intput type  is string
    let r = serde_json::from_str::<Res>(s).unwrap(); // 
    println!("{:?}", r);
}

```

result:
> Res { r: 1, d: None }

I expect deserializing `s` would fail since they have different types. Any idea about this?

**Comment by wackazong** [comment]
In the exact case above I think you can work around this using the example here with `serde(transparent)` https://github.com/serde-rs/json/issues/765

**Comment by dtolnay** [comment]
I think this is the intended semantics for `flatten` on `Option`. When you use `flatten`, you don't explicitly describe a heuristic for deciding whether the input data contains that thing or not. It effectively operates like `#[serde(untagged)] enum Option<T> { Some(T), None }`.

A more sophisticated heuristic would need to be implemented by handwriting the Deserialize impl for `Res`, using knowledge about the structure of `Data` to decide based on the information in the input whether a `Data` is present or not.

**Comment by Mingun** [comment]
Actually, the reason of current behavior is that is another instance of #1183

**Comment by dtolnay** [comment]
I don't think it is? This is dedicated behavior implemented intentionally in #1256. I don't think it's correct to expect that if buffering were not used, so that the underlying data format were directly in charge of deserializing the inner `Data`, then there would necessarily be a way to tell the difference unambiguously between "input contains `Data`, but not matching the required structure for `Data` properly, so error" vs "input contains something other than `Data`".

**Comment by philpax** [comment]
Just ran into this with
```rust
#[derive(Deserialize, Clone, Debug, PartialEq, Serialize)]
pub struct Dependency {
    // ...
    #[serde(default, flatten)]
    pub package_version: Option<DependencyPackageVersion>,
}
#[derive(Deserialize, Clone, Debug, PartialEq, Serialize)]
pub struct DependencyPackageVersion {
    pub id: PackageId,
    pub version: String,
}
```

which results in a `None` `package_version` for `{ id = "jhsdfu574S", version = "0.1.0" }`. This isn't an issue - I can just manually flatten and check for both fields - but it _is_ a bit counter-intuitive.

I'm not sure how this could be improved; `serde` could error on this specific case and tell users to rework it, but I assume the current behaviour has intentional use cases?

**Comment by dtheodor** [comment]
This behavior is unexpected. It gives additional semantics to flatten beyond "as-if it was not nested"
