### ISSUE TITLE
Shorthand for #[serde(skip_serializing_if = "Option::is_none")] #[serde(default)]

### ISSUE THREAD

**Issue by kangalioo** [serde-rs/serde#1932]
This is a use case I've encountered repeatedly in the project I'm currently working on: a struct field of type `Option<T>` is always omitted from the serialized representation if it is `None`. This can currently be achieved in serde with two field attributes:
```rust
struct Foo {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    bar: Option<u32>,
}
```

It would be very pleasant to have a shorthand for this usecase. `#[serde(flatten)]` would make sense semantically

**Comment by jonasbb** [comment]
There is nothing in serde like that. You can use other crates to achieve this, like [`serde_with::skip_serializing_none`](https://docs.rs/serde_with/1.6.0/serde_with/attr.skip_serializing_none.html).
You do not need `#[serde(default)]` on a field of type `Option`. serde deserializes them to `None` if they are missing by default ([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c9bd89735c820e3ebf0712be83d68875)).

**Comment by jhartzell42** [comment]
Why is `skip_serializing_none` not in `serde` itself?

**Comment by dtolnay** [comment]
I'll close this since I think this issue was filed under the impression that your use case requires both attributes (`skip_serializing_if` and `default`). Since only `skip_serializing_if` is needed as explained in https://github.com/serde-rs/serde/issues/1932#issuecomment-739059937, I don't think a shorthand is needed here.
