### ISSUE TITLE
Serde Apache License is Not Filled In

### ISSUE THREAD

**Issue by Alexei-B** [serde-rs/serde#1939]
Yo you forgot to fill the boilerplate to your license in! 😛 
https://github.com/serde-rs/serde/blob/master/LICENSE-APACHE

![image](https://user-images.githubusercontent.com/876187/103377484-6ce05f80-4ad7-11eb-9420-05ff0b530938.png)

**Comment by dtolnay** [comment]
We do not use boilerplate notices in source files because it is not a requirement for effecting the Apache license. Refer to https://github.com/rust-lang/rust/pull/43498 or https://github.com/rust-lang/rust/pull/57108.

The snippet *in LICENSE-APACHE itself* (as opposed to source files) is not intended to be modified.

**Comment by Alexei-B** [comment]
Fair enough seems strange when you read it but that works.

**Comment by dtolnay** [comment]
> Not sure the appendix is actually part of the license but I guess it could be viewed as such, sure.

The appendix is not part of the license. It instructs the recipient how to apply the terms and conditions of the license to their work should they choose.
