### ISSUE TITLE
Module export is private in 1.0.119

### ISSUE THREAD

**Issue by dswd** [serde-rs/serde#1950]
Hi, I get this error in the automatic dependabot builds of my project for 1.0.119.
My code did not change in between, the only difference is serde 1.0.119 vs 1.0.118.

```
error[E0603]: module `export` is private
Error:    --> src/config.rs:31:10
    |
31  | #[derive(Deserialize, Debug, PartialEq, Clone)]
    |          ^^^^^^^^^^^ private module
    |
note: the module `export` is defined here
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.119/src/lib.rs:275:5
    |
275 | use self::__private as export;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by dtolnay** [comment]
That module has never been a public API. It has always been hidden and commented "not public API":

https://github.com/serde-rs/serde/blob/e7974312681c9c1c54f7586e86b0d7013b350a54/serde/src/lib.rs#L267-L269

**Comment by dtolnay** [comment]
Oops, this isn't just a duplicate of #1949!

In https://github.com/dswd/vpncloud/pull/134/files this is caused by using a new version of serde with an old version of serde_derive, which is not supported. Those should always have the same version number or alternatively you'll need to use derives through the serde crate as described in https://serde.rs/derive.html.

**Comment by Progdrasil** [comment]
Even if this was never a public API but downstream applications relied on it, shouldn't the change in 1.0.119 be considered a breaking change? Since it requires all dependent libraries that have depended on this module to update their dependent versions which most likely expect a bump in a revision number not to be breaking their code.

**Comment by dtolnay** [comment]
Nope, breaking change (in the context of semver) only refers to public APIs &mdash; check https://semver.org. Something that is not a public API (such as something that is explicitly commented "Not public API") has no bearing on semver numbering.

In general there are lots of things that are not semver breaking changes which can cause incorrect downstream code to break.
