### ISSUE TITLE
Allow skipping an enum variant

### ISSUE THREAD

**Issue by ctron** [serde-rs/serde#2062]
For enum variants there exists the option to `#[serde(skip)]`. However, this actually fails the serialization process, instead of skipping the variant.

I would expect that there is a way to skip serializing an enum variant like this:

~~~rust
enum Foo {
   Bar,
   #[serde(skip, other)]
   Baz,
}

impl Default for Foo { fn default() -> Self { Self::Baz} }
~~~

Resulting in (for Bar):

~~~json
{ "Bar" }
~~~

And resulting in (for Baz):

~~~json
{}
~~~

**Comment by jonasbb** [comment]
If I understand this correctly, you want that serializing `Foo::Baz` simply does nothing instead of returning an error. This is not really possible with the function signature for serializing
`fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>`, since obtaining a `S::Ok` is only possible by serializing a value.

You can skip serializing fields of a struct using `skip_serializing_if`:
```rust
#[derive(serde::Serialize)]
struct S {
    f1: Foo,
    #[serde(skip_serializing_if = "is_default")]
    f2: Foo,
}
```
[Example on Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=414770aca1b596951078440faf9a0854)

**Comment by ctron** [comment]
> If I understand this correctly, you want that serializing `Foo::Baz` simply does nothing instead of returning an error.

Correct.

I was able to get close to this behavior using a custom serializer:

~~~rust
#[derive(Clone, Debug, Deserialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub enum DownstreamSpec {
    ExternalKafka(ExternalKafkaSpec),
    #[serde(other)]
    Internal,
}

impl Serialize for DownstreamSpec {
    fn serialize<S>(&self, s: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut s = s.serialize_struct("externalKafka", 0)?;
        match self {
            Self::ExternalKafka(kafka) => {
                s.serialize_field("externalKafka", &kafka)?;
            }
            Self::Internal => {}
        }
        s.end()
    }
}
~~~

I still have the issue that `other` still expects some value:

Works:
~~~json
{"downstream": "foo"}
{"downstream": "internal"}
{"downstream": { "externalKafka": {}}
~~~

Fails:
~~~json
{"downstream": {}}
{"downstream": { "foo":{}}
~~~

I would expect that either string or struct both work of the "other" variant, as I don't have `deny_unknown_fields` set. I guess a custom deserializer would work too :grinning:

**Comment by dtolnay** [comment]
I'll close since I don't expect to make implementation changes related to this, but if you still need guidance getting something to serialize/deserialize in the way that you have in mind, feel free to take this to one of the resources listed in https://github.com/serde-rs/serde/tree/v1.0.135#getting-help.
