### ISSUE TITLE
Deserialize the same field twice 

### ISSUE THREAD

**Issue by avnerbarr** [serde-rs/serde#2180]
I want to deserialize the same field twice into 2 separate named fields

I've tried using "alias" as well as "rename" attributes but not successful:

```
use serde::Deserialize;
    use serde::Serialize;
    use serde_json::json;

    #[derive(Serialize, Deserialize, Debug)]
    struct Example {
        pub a: i32,
        #[serde(rename(deserialize = "a"))]
        //#[serde(alias = "a")] // tried this as well
        pub b: i32,
    }

    #[test]
    fn test_example() {
        let example = Example { a: 0, b: 1 };

        let s = serde_json::to_string_pretty(&example);
        println!("{:?}", s);

        let js = json!({
            "a" : 12,
            "c" : 32
        });
        let res = serde_json::from_value::<Example>(js);
        println!("{:?}", res);
    }

```

once that is possible, I would like to also have a custom deserialize function for the second occurrence since I need to apply a slight modification

**Comment by Lucretiel** [comment]
You'd need to manually implement `Deserialize` for this type. Deserialization is inherently sort of a single-shot process; every operation can generally only be performed once. A `Deserializer` can only produce one value; a `Visitor` can only be visited once, etc. Serde (usually) won't copy / clone data for you, since this requires buffering all the data that it might want to clone. Your best bet would be to manually implement `Deserialize`.
