### ISSUE TITLE
Reading custom attributes in custom serialization & deserialization

### ISSUE THREAD

**Issue by tejHackerDEV** [serde-rs/serde#2309]
Hi, I am looking for a way to read custom attributes defined on a struct in my custom serialization & deserialization so that I can perform my own custom impl for the fields while serializing & deserializing

```Rust
#[serde(custom_attribute)] 
pub struct User {
    #[serde(with = "hex_string")]
    id: Option<String>,
    email: String,
    #[serde(another_custom_attribute)] 
    password: String,
}
```

**Comment by dtolnay** [comment]
This is not something I would be interested in supporting in this crate. The way you customize an impl is by writing the code for the impl.

**Comment by tejHackerDEV** [comment]
Hi @dtolnay, sorry for my english, I may be sounded incorrectly. what I am saying is I want to customize the struct in the impl block only, but in order to do that I want to read my custom attributes that I am defining above the fields in my impl block (inside serializers & deserializers). 

Like let's suppose say I have a user struct & I want to remove some fields like password in the responses sending to front-end but not in the backend program, then I want to annotate the field like as private or any other like [this](https://github.com/hagopj13/node-express-boilerplate/blob/master/src/models/user.model.js#L36). And later on, I want to use serde_json by changing the responses like the same way you proposed in [serde_json issue](https://github.com/serde-rs/json/issues/513#issuecomment-460943687). Hope it clarifies now, what I am asking or else I am happy to explain a bit more verbosely if needed.

**Comment by tejHackerDEV** [comment]
Hello @dtolnay, any thoughts about this?

**Comment by martin-g** [comment]
Apologies for commenting on closed issue!

I also want to do the same - depending on whether the enum has specific (container or field) attribute I want to use a specific (De)Serializer or the same (De)Serializer but having some context information about the applied attributes, so that it can decide at runtime what to do.
Something like Java runtime annotations and reflection APIs.

Let's say I have:
```rust
#[my(attribute)]
enum Enum {
 A(i32),
 B {
   number: i64
 }
}

struct Struct {
  s: String,
  e: Enum
}
```

Usually I do:
```rust
let value = Struct { ... };
let mut serializer = MySerializer::default();
value.serialize(&mut serializer)
```

serde.rs would call MySerializer's 
```rust
fn serialize_struct_variant(
        self,
        enum_name: &'static str,
        index: u32,
        variant: &'static str,
        len: usize,
    )
```
and here I want to be able to decide what to do depending on whether `#[my(attribute)]` is applied on the enum or not.

As far as I can see this is not possible currently with serde-rs because the `serialize_xyz_variant` methods do not bring any context information.
But also Rust attributes are not available at runtime as Java annotations, so I am not sure it is even possible.

Any ideas how to achieve this use case are very welcome!
