### ISSUE TITLE
Publish serde.rs on docs.rs

### ISSUE THREAD

**Issue by arniu** [serde-rs/serde#2352]
It's very slooow to visit <https://serde.rs/> in some countries. 
How about to publish it on <https://docs.rs/> as a crate `serde-docs` or just a mod of  the `serde` crate enabled by a feature `docs`?

**Comment by dtolnay** [comment]
I am not going to be interested in pursuing this myself. But the book content is appropriately licensed such that someone else could feel free to try hosting it in a faster system.

If there are any suggestions or reading material for how I can make serde.rs faster in your country, I am open to that. It's just Cloudflare in front of a GitHub Pages site. It doesn't sound like the .rs tld has anything to do with it, since you find that docs.rs isn't slow?
