### ISSUE TITLE
How to enforce key order when deserializing?

### ISSUE THREAD

**Issue by morr0ne** [serde-rs/serde#2368]
I am currently trying to write a bencode decoder/encoder using serde for [my torrent client.](https://github.com/morr0ne/leech/tree/complete-bencode-encoder) I am facing a bit of a problem when trying to enforce the key ordering mandated by the [bencode specification](https://www.bittorrent.org/beps/bep_0003.html). Nothing I have tried so far seems to be working so I was hoping someone with a better understanding of serde internals might be able to help me.

The problem basically boils down to the following:
When serializing a struct/map I need to make sure that the keys are sorted. At first I thought I could simply write:
```rust
fn serialize_key<T: ?Sized>(&mut self, key: &T) -> Result<()>
where
    T: Serialize,
{
    key.serialize(&mut **self)
}
fn serialize_value<T: ?Sized>(&mut self, value: &T) -> Result<()>
where
    T: Serialize,
{
    value.serialize(&mut **self)
}
```
And then somehow tell serde to serialize the key in a sorted manner. Unfortunately there does not seem to be way to achieve such a thing. The next thing that I tried is to delegate the job of serializing a struct/map to a specialized [StructSerializer](https://github.com/morr0ne/leech/blob/3f1eeededb7243ebf628cb9085a25998072be978/bencode/src/ser.rs#L37) that would buffer everything into a BTreeMap. This is not ideal for performance but it should work fine. However I am simply to able to pull this off:
```rust
pub struct StructSerializer<'a, W: 'a> {
    serializer: &'a mut Serializer<W>,
    dictionary: BTreeMap<&'static str, ???>, // What should this type even be?
}

impl<'a, W> ser::SerializeMap for StructSerializer<'a, W>
where
    W: std::io::Write,
{
    fn serialize_entry<K: ?Sized, V: ?Sized>(
        &mut self,
        key: &K,
        value: &V,
    ) -> Result<(), Self::Error>
    where
        K: Serialize,
        V: Serialize,
    {
        self.dictionary.insert(key, value); // I can't insert them because they are not concrete types yet

        Ok(())
    }
}
```
Somehow I need to be able to store the key and value inside the BTreeMap but I have no idea how, they are not concrete types yet but I need to preserve them since I still need to serialize them later on.

I hope any of this made sense because I have been fighting with serde for the last week without any progress. Any kind of help would be greatly appreciated.

**Comment by jonasbb** [comment]
> And then somehow tell serde to serialize the key in a sorted manner.

serde is not in charge of the key order. Each individual `Serialize` implementation is in charge of it. Most of them are generated by `serde_derive`. So if you target a limited set of types you control, a special derive which emits keys in sorted order might help. For a general applicable solution you will need to buffer in the `Serializer`.

> Somehow I need to be able to store the key and value inside the BTreeMap but I have no idea how, they are not concrete types yet but I need to preserve them since I still need to serialize them later on.

Yes, you will not be able to store `key` and `value` here. Also because you only get a reference to them which may not outlive the function. What you can do is to serialize both `key` and `value` and then store the serialized form. The serialized form could either be a high-level value like type, such as the `Content` type serde carries.

https://github.com/serde-rs/serde/blob/b7be637e8cf73dcbea28c6ea960604371726171d/serde/src/private/ser.rs#L428-L469

You can take inspiration by other bencode serializers, like bendy:

https://github.com/P3KI/bendy/blob/914792ab63509c0a5f45a3aad3fa157a0b25849a/src/serde/ser/struct_serializer.rs#L9C3-L46

Here it looks like each value is encoded into bencode, then buffered. After the struct ist done, all key-value pairs are emitted in sorted order.
