### ISSUE TITLE
`#[serde(default)]` stack overflow

### ISSUE THREAD

**Issue by MaxKingPor** [serde-rs/serde#2484]
# Example
``` Rust
pub static PROFILE: &str = include_str!("profile.toml");

#[derive(Debug, serde::Serialize, serde::Deserialize, Clone)]
#[serde(default)]
struct Test {
    arg1: i32,
    arg2: i32,
}

impl Default for Test {
    fn default() -> Self {
        //  toml::from_str(PROFILE).unwrap()
        toml::from_str(
            r#"
        arg1 = 123
        arg2 = 123
        "#,
        )
        .unwrap()
    }
}

#[test]
fn test_toml() {
    let r: Result<Test, _> = toml::from_str(
        r#"
        arg1 = 123
        arg2 = 123
        "#,
    );
    println!("toml {:?}", r);
}
```

**Comment by Mingun** [comment]
This is because you use `Deserialize::deserialize` impl in your `Default` impl. `#[serde(default)]` on a type [leads to generation](https://github.com/serde-rs/serde/blob/c0ba323166c78d13c1c8d666a551b14229b87d9e/serde_derive/src/de.rs#L2666-L2678) of a default instance even when all fields are set.

There is [an issue](https://github.com/serde-rs/serde/issues/2345) to make `default()` call lazy, but I anyway recommend do not use your idiom, because if you add new fields then you silently add this stack overflow bug again

**Comment by fritzrehde** [comment]
If you don't recommend putting `#[serde(default)]` above a whole struct, is there any other way to tell serde to use the default implementation for each member if it wasn't provided? This seems like commonly used functionality, and adding `#[serde(default)]` to each member is a lot of unnecessary boilerplate.

**Comment by Mingun** [comment]
@fritzrehde, if you about my recommendation it was about using deserialize in `Default` implementation as in topic-starter example. Instead of that it is better to just construct type as usual. Or write a custom proc-macro which would generate construction literal if you want to take defaults from the serialized form in your repo.
