### ISSUE TITLE
Reproducing the precompiled executable

### ISSUE THREAD

**Issue by bjorn3** [serde-rs/serde#2575]
It seems you used a nightly version of rustc (rustc version 1.73.0-nightly (f3623871c 2023-08-06)), but which linker version and which musl version? And what `Cargo.lock` was used? How can I reproduce a bit for bit identical executable?

https://reproducible-builds.org/

**Comment by dvdsk** [comment]
I think we can take this a bit further. How about building the executable on Github CI? Then the method of creating the executable is documented in the repo. It would be trivial to replicate (fork the repo and run CI). The executable itself might even be added/replaced on each release by CI. That might ease maintenance.

Can anyone with experience and or real knowledge with supply chain security pitch in if this could work?

(at the very least this approach seems to assume GitHub is trusted).

**Comment by messense** [comment]
> How about building the executable on Github CI?

+1 for this. It'd be nice to also publish [sigstore](https://www.sigstore.dev/) signatures using [sigstore/gh-action-sigstore-python](https://github.com/sigstore/gh-action-sigstore-python).

**Comment by frank10gm** [comment]
It would be preferable to avoid using precompiled binaries altogether.

**Comment by dvdsk** [comment]
> It would be preferable to avoid using precompiled binaries altogether.

Lets keep on subject before this issue derails and any useful comments get drowned out. If you have unrelated problems or ideas please add them to an existing issue that specifically addresses those if it exists or open a new issue. 

Though it might make Microsoft very happy lets not turn GitHub into a new social media platform :)

**Comment by dtolnay** [comment]
From examining the diffoscope comparison in https://github.com/serde-rs/serde/issues/2538#issuecomment-1684117378 between my build and one inside `rust:alpine` (https://pkgbuild.com/~kpcyrd/2023-08-18-serde-derive-forensics/diffoscope-serde_derive-1.0.177.html), I think the differences are:

1. Initially, a different choice of nightly rustc, which means the standard library contains different code and the compiler contains different optimizations. I think build.sh should be updated to run `cargo +nightly-YYYY-MM-DD build` with a particular date, rather than latest `+nightly`.

2. Different linker &mdash; this would account for the presence or absence of a GNU build-id note in the program header, leading to various 1-word offsets.

3. Different version of the quote and syn dependencies. I checked the changes here since July 27 and I don't immediately see any that would make a difference other than in debuginfo (which is not present), so I don't know if these are a factor, but it's something that needs to be addressed anyway with a lockfile going forward.

For number 2, probably docker is the easiest way to reconcile this? If so, I would love to accept a PR that updates build.sh to run docker (/ podman?) with some usefully pinned base image and copies the result out.

**Comment by aDotInTheVoid** [comment]
Would you mind sharing what linux distro and linker version you used to build the existing precompilled binaries?

**Comment by dtolnay** [comment]
```console
$ cat /etc/issue
Ubuntu 22.04.3 LTS \n

$ ld --version
GNU ld (GNU Binutils for Ubuntu) 2.38
Copyright (C) 2022 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

**Comment by aDotInTheVoid** [comment]
[I've got marginally closer to reproducing](https://htmlpreview.github.io/?https://github.com/aDotInTheVoid/serde-bitwise-reproduction/blob/trunk/diff1.html), using the same rustc version and linker. It now has the same elf header. Relocations still seem different.

[Code here](https://github.com/aDotInTheVoid/serde-bitwise-reproduction/tree/2ca9b600d562f41e38696e386a67b1b0d0c2e5eb). Sorry it's a bit of a mess. My hypothesis is different dependency versions may change relocations, even if not code. I'll investigate more tomorrow (unless someone else solves it)

**Comment by V0ldek** [comment]
Since the idea of relying on GitHub CI was thrown around, let me chime in that if the binary is indeed the direction going forward, it should be the only acceptable choice.

If serde wants to do this, do it right: maintain and verify the binary's **provenance**.

Implementing [SLSA](https://slsa.dev/) for Rust builds is very easy in GitHub CI (see [SLSA GitHub Generator - Provenance for Rust](https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/generic/README.md#provenance-for-rust). It would give all users an attestation that the binary included with their `serde` was verifiably built by this repo's CI, from available source, without tampering.

There's quite a few high-profile projects that implement SLSA (e.g. Python's flask). It would be a good thing for the Rust community to have a high-profile project that also treats supply-chain vulnerabilities with a high level of importance.

**Comment by LikeLakers2** [comment]
I support V0ldek's suggestion here. Normally I would simply leave a react, but I feel it's important to explain why I support it.

As a user of `serde`, I'm not a big fan of the precompiled executable stuff. The main problem (but definitely not the only problem) I have with it is that it forces me to trust dtolnay in a manner that makes me (and, as I can tell, many others) uncomfortable: We have to trust that dtolnay (or even a third-party) hasn't tampered with the executable that he's packaged into `serde_derive`. I would much rather just build `serde_derive` from scratch every build than need to trust dtolnay in that manner.

However, the suggestion proposed in V0ldek's comment feels far more comfortable to me. It allows dtolnay to precompile `serde_derive` without me needing to worry about if the binary was edited before distribution.

Hence, I support V0ldek's suggestion.

**Comment by MinisculeGirraffe** [comment]
> We have to trust that dtolnay (or even a third-party) hasn't tampered with the executable that he's packaged into serde_derive

I'd say that it's perfectly reasonable to trust @dtolnay, I think the third party part is the more important risk.

Binary blobs are a lot like STDs in the sense that you're not just dealing with just this binary, you're dealing with all the other software that's running on the machine at compilation time.  Unless you can completely trust the machine the binary was built on, you can't trust the binary. Trust in the maintainer has nothing to do with it.  It's better to get hacked because my machine was running insecure software, rather than getting hacked because someone else's machine was. 

If an opt-in approach to it isn't possible, a verifiably built binary from the repo's CI is a significant improvement from the existing model

**Comment by dbischof90** [comment]
> > We have to trust that dtolnay (or even a third-party) hasn't tampered with the executable that he's packaged into serde_derive
> 
> 
> 
> I'd say that it's perfectly reasonable to trust @dtolnay, I think the third party part is the more important risk.
> 
> 
> 
> Binary blobs are a lot like STDs in the sense that you're not just dealing with just this binary, you're dealing with all the other software that's running on the machine at compilation time.  Unless you can completely trust the machine the binary was built on, you can't trust the binary. Trust in the maintainer has nothing to do with it.  It's better to get hacked because my machine was running insecure software, rather than getting hacked because someone else's machine was. 
> 
> 
> 
> If an opt-in approach to it isn't possible, a verifiably built binary from the repo's CI is a significant improvement from the existing model

To be fair, that would make @dtolnay s credentials the potential weak spot. Just because his accounts commits and signs a check does not mean it's literally him. I would also, if absolutely necessary, not have that assumption as the point of failure in hundreds of projects, including the compiler itself.


Are there mechanics to have a separately signed binary stored with an audited service, whose authenticity can be checked before I update my crates? That should be a reasonable minimal base for requiring users to download a binary based on good faith.

**Comment by LikeLakers2** [comment]
> I'd say that it's perfectly reasonable to trust @dtolnay, I think the third party part is the more important risk.

I think you're missing the point here. I *do* trust dtolnay. But I shouldn't need to have faith that dtolnay is doing everything right.

That's why I'm against the precompiled executable stuff - and for the suggestion V0ldek made. If I can verify an executable I downloaded against one that was compiled by a source I trust (i.e. Github Actions, or one compiled by my own computer), I will feel a lot more comfortable using that executable.

But right now, there's no way to verify that dtolnay isn't tampering with the file - especially since people are having trouble reproducing the executables (as evidenced by this very issue).

**Comment by kayabaNerve** [comment]
To clarify, if a GH CI-based path is taken, how feasible would that to be locally reproduce? I understand how to locally reproduce Docker-based solutions, yet haven't tried locally setting up a GH CI runner.

**Comment by yaleman** [comment]
Part of the attestation should include information on how it was generated, package versions, environment etc, but Docker-in-GHA is also an option to make that easier.

**Comment by V0ldek** [comment]
> To clarify, if a GH CI-based path is taken, how feasible would that to be locally reproduce? I understand how to locally reproduce Docker-based solutions, yet haven't tried locally setting up a GH CI runner.

SLSA provenance would give enough information to fully reproduce the build &ndash; GH CI can be run locally.

That's in theory. In practice it would be much easier for people to reproduce if it was a Docker-based build (most people interested most likely have Docker, or would be able to set it up quickly enough). 

SLSA has [a generator for Docker-based builds as well](https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/docker/README.md).

---

As for some of the other discussion, I think it's good to grasp the benefit that SLSA lvl. 3 provenance would give &ndash; anyone would be able to independently check that the binary used during build of `serde_derive` is:

1. produced by the CI Action in this repository,
2. from a particular run of the Action,
3. which is 1-1 tied to a particular commit hash.

The source code used for the build (and the pipeline logic) is auditable and reproducible. Then, you can also automatically verify that the bin included in the crate is actually the result of that specific build. Provenance is signed by GH, so to break all this the attacker would need to compromise both the authors' creds to crates.io, _and_ hosted GH runners; and at that point we can all pack and go home anyway, the binary isn't even necessary for such a powerful attacker model.

**Comment by kayabaNerve** [comment]
If in practice a Docker-based solution would be "much easier", that sounds like the goal to have.

**Comment by jayvdb** [comment]
This issue may no longer be relevant since https://github.com/serde-rs/serde/releases/tag/v1.0.184 removed the pre-compiled binaries.

**Comment by dtolnay** [comment]
I intentionally kept this open because some people are likely still interested in ascertaining exactly what got run in their environment over the past 4 weeks, for forensic purposes.

**Comment by dtolnay** [comment]
The Docker / SLSA discussion is no longer going to be relevant, but https://github.com/serde-rs/serde/issues/2575#issuecomment-1685130259 + https://github.com/serde-rs/serde/issues/2575#issuecomment-1685177585 are still important if anyone is trying to reproduce the old builds.

**Comment by wucke13** [comment]
Just another throw-in: If reproducibility is a concern, it would be possible to provide a Nix build script for the binary. Provided that one has any recent version of nix, that should take out almost every variability out of the build.

**Comment by faulesocke** [comment]
Why not just drop the executable entirely instead?

**Comment by faulesocke** [comment]
Am I correct with the assumption, that the pre-compiled binary is gone and will stay gone and this issue only exists for documentation purposes now?

**Comment by jayvdb** [comment]
@faulesocke , yes, this issue only exists for anyone who is worried that the binary that they *were* using could have been nefarious.  I believe there is an extremely small number of people for whom that is an ongoing concern , given the binary behaved as it should have, had all the expected symbols, and the author is respected and is not compromised.

> ... and will stay gone ...

According to the [release](https://github.com/serde-rs/serde/releases/tag/v1.0.184) :

> eventually we'd like to use a first-class precompiled macro if such a thing becomes supported by cargo / crates.io

So it should come back in the future, but only when that approach is blessed & supported by the Rust team.

**Comment by jhpratt** [comment]
@dtolnay Were the binaries fully reproduced? If not, why close the issue? As you said, it's still useful to know for the ~month that they were present.
