### ISSUE TITLE
#[serde(deserialize_with=...)] should not require a field to implement Deserialize

### ISSUE THREAD

**Issue by erickt** [serde-rs/serde#259]
Unfortunately there's a gap in the current implementation of `#[serde(deserialize_with="...")]`. First, it's not getting used in the `Visitor::visit_seq` method, and two, it's interacting poorly with `serde::de::MapVisitor::missing_field`, which is called when a value is missing. This is necessary for formats like json, which typically interpret missing fields as a `null` value.

**Comment by dtolnay** [comment]
> First, it's not getting used in the `Visitor::visit_seq` method

I fixed this in https://github.com/serde-rs/serde/pull/285/commits/886670134a5382bc181cd44b93592712e7c01076#diff-34bac2079ee371621845dc9670e2e20fR521.

> two, it's interacting poorly with `serde::de::MapVisitor::missing_field`

@erickt if you have any thoughts of how to resolve this, I have some time to implement it.

**Comment by dtolnay** [comment]
I have one possible solution to this in https://github.com/dtolnay/serde/pull/1 (it conflicts with #308 so I am holding off on making a PR here).

The solution is, if a field is missing:

1. If there is a default expression, use the default expression (this includes `skip_deserializing`).
2. If the field has `deserialize_with`, fail with `Visitor::Error::missing_field(name)`.
3. Otherwise call `visitor.missing_field(name)` to possibly handle the field.

This means `deserialize_with` no longer goes through the visitor's `missing_field`, instead failing directly unless there is a default. Thus fields with `deserialize_with` do not require `Deserialize` as a bound. The missing field behavior can be controlled by setting a default for the field.

**Comment by dtolnay** [comment]
Fixed in #311, can be closed.
