### ISSUE TITLE
Deserialize errors when using `#[serde(flatten)]` with HashMap<usize, T>

### ISSUE THREAD

**Issue by r4ve1** [serde-rs/serde#2628]
```rs
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Deserialize, Serialize, Debug)]
struct A {
    #[serde(flatten)]
    b: B,
}

#[derive(Deserialize, Serialize, Debug)]
struct B {
    map: HashMap<usize, String>,
}

fn main() {
    let a = A {
        b: B {
            map: HashMap::from([(1, "a".to_string()), (2, "b".to_string())]),
        },
    };
    let s = serde_json::to_string(&a).unwrap();
    println!("{}", s);
    let aa: A = serde_json::from_str(&s).unwrap();
    // thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: string \"1\", expected usize", line: 1, column: 25)', src\main.rs:23:42
    println!("{:?}", aa);
}
```

however when deleting the `#[serde(flatten)]` the deserialize won't error

**Comment by Mingun** [comment]
This is duplicate of #1183. In JSON map keys can be only strings, so `serde_json::Deserializer::deserialize_any` returns strings to you. Flattening buffers the input using generic deserializer that uses `serde_json::Deserializer::deserialize_any` to capture data and then provide then. Unfortunately, because it is general, it is not aware that it's responsibility of the JSON key deserializer to convert strings to integers. From the other hand, `usize::deserialize` doesn't accept strings as valid input and returns error that you're see.

**Comment by r4ve1** [comment]
I see, thanks
