### ISSUE TITLE
Can't reuse extra fields when deserializing structs

### ISSUE THREAD

**Issue by alexcrichton** [serde-rs/serde#267]
Let's say you've got a struct:

``` rust
#[derive(Deserialize)]
struct Foo {
    a: i32,
}
```

and let's say you've got a TOML document:

``` toml
a = 3
b = 4
```

Right now the toml-rs crate supports a feature where if you deserialize the TOML document into a `Foo`, you can get back the original TOML document with the fields of `Foo` missing, for example this would return the TOML document:

``` toml
b = 4
```

This support was implementable in serde 0.6, but unfortunately in 0.7 the expansion for `#[derive(Deserialize)]` now uses the `IgnoredAny` visitor for any unknown struct fields. This means that any unknown struct fields aren't known to the deserializer, so the toml-rs crate isn't able to give back the unused keys.

So I guess my questions are:
1. Is this true? Can this behavior actually be supported on 0.7?
2. Is this intentional? Is this behavior _supposed_ to not be supported by serde?

**Comment by oli-obk** [comment]
The PR of the first impl is #201 and the actually merged PR is #204

So you can slap `#[serde(deny_unknown_fields)` onto the structs that should error instead of silently allow unknown fields. It's documented under [`Annotations`](https://github.com/serde-rs/serde#annotations)

**Comment by erickt** [comment]
cc-ing @JohnHeitmann

@alexcrichton: you keep using serialization in unexpected ways :) As you probably have guessed, I haven't really considered this use case, but I think we can come up with something that doesn't consume your unknown values. Unfortunately, the way `IgnoredAny` works is that it's passing in a generic visitor that's supposed to consume any value that you could pass into it, which is what you'd want for a deserializer that's ignorant of `IgnoredAny`. But since you want to do something special, you could switch to a different deserializer that does what you want:

```rust
    fn deserialize_ignored_any<V>(&mut self, visitor: V) -> Result<V::Value, Self::Error>
        where V: Visitor
    {
        use serde::de::value::ValueDeserializer;
        <() as ValueDeserializer<Self::Error>>::deserialize(visitor)
    }
```

This exploits the fact that the `IgnoredAnyVisitor` really doesn't care what value gets passed into it, so we'll cheat and just pass in a `()` value. That wouldn't touch your internal toml state, so you should be able to still produce a `.toml` file with all your missing values.

This also suggests that the current design might not be quite right. The fact that `Deserializer::deserialize_ignored_any` is parameterized means that you need to use the visitor in order to return the right type. It's written this way so it could fall back onto `Deserializer::deserialize`, but thinking about that now, I don't think we actually need it. Instead we could rewrite this in v0.8 to:

```rust
    fn deserialize_ignored_any(&mut self) -> Result<(), Self::Error>;
```

Which would allow you to do what you want without needing to have a sub-deserializer. I've filed this ticket as a 0.8 enhancement request for consideration when we start working on the next major release.

**Comment by alexcrichton** [comment]
Thanks @erickt! That does indeed work for now!

**Comment by JohnHeitmann** [comment]
What's the ultimate purpose for retaining the unknown fields? Are you formatting unknown keys (and keys only) into an error message, or do you want to retain the full TOML representation for some larger reason?

If it's for error reporting, maybe the right thing to do is return more semantic information in the error from ``#[serde(deny_unknown_fields)`` validation.

**Comment by JohnHeitmann** [comment]
... but my suggestion isn't great if you want a warning, since you only get a Result xor Error now.

Someone in the original discussion wanted a formal outlet to listen for unknown fields. I discounted that since I was in a web services mindset and didn't see a compelling reason, but validation warnings for file formats is a pretty good one.

**Comment by alexcrichton** [comment]
@JohnHeitmann the purpose currently is for Cargo to warn about unused keys in `Cargo.toml`, so getting a document back with all the extra keys helps us print out all the keys which weren't used.

**Comment by dtolnay** [comment]
The DeserializeSeed mechanism added in 0.9 makes it possible to solve this in a generalized way.

https://github.com/dtolnay/serde-ignored
