### ISSUE TITLE
Deserialize object/map while maintaining order

### ISSUE THREAD

**Issue by calebmer** [serde-rs/serde#269]
Is there a way to deserialize a map (like a JSON or YAML object) while maintaining the order of key/value pairs? The `BTreeMap` type deserializes into kind of what I want except it does not maintain order.

Deserializing a map to `Vec<(K, V)>` would be perfect.

**Comment by dtolnay** [comment]
Using an ordered map type would be more appropriate than `Vec<(K, V)>`. I found a [linked hash map implementation](https://crates.io/crates/linked-hash-map) and made a PR to add Serde support: https://github.com/contain-rs/linked-hash-map/pull/48

Unfortunately, LinkedHashMap will work for JSON but not [serde-yaml](https://github.com/dtolnay/serde-yaml) because serde-yaml uses yaml_rust which uses a [BTreeMap for maps](http://chyh1990.github.io/yaml-rust/doc/yaml_rust/yaml/type.Hash.html).

**Comment by dtolnay** [comment]
I made a PR that adds a preserve_order feature to yaml-rust: https://github.com/chyh1990/yaml-rust/pull/16. Once that merges and yaml-rust does a 0.3.1 release, I can update serde-yaml to depend on it: https://github.com/dtolnay/serde-yaml/pull/14.

I will check off the PRs as they merge:

- [ ] https://github.com/contain-rs/linked-hash-map/pull/48
- [ ] https://github.com/chyh1990/yaml-rust/pull/16
- [ ] https://github.com/dtolnay/serde-yaml/pull/14

**Comment by calebmer** [comment]
Awesome, thanks so much! If you need anything from me feel free to ask 😊

**Comment by dtolnay** [comment]
All set here, I think. The answer is to use an ordered map type ([linked-hash-map](https://github.com/contain-rs/linked-hash-map) and [linear-map](https://github.com/contain-rs/linear-map) both come with serde support). For YAML you additionally need to set the `preserve_order` feature flag to force yaml-rust to use LinkedHashMap instead of BTreeMap. This issue can be closed.

**Comment by oli-obk** [comment]
Should we add this feature to the json value type?

**Comment by calebmer** [comment]
Awesome, thanks! @oli-obk, maybe that should be a fresh issue?

**Comment by dtolnay** [comment]
I filed https://github.com/serde-rs/json/issues/54 to follow up on adding a feature flag to use linked-hash-map in serde_json::Value.
