### ISSUE TITLE
Shall Serde be also called Serialize?

### ISSUE THREAD

**Issue by vi** [serde-rs/serde#270]
So far the [serialize crate](https://crates.io/crates/serialize) does not exist, but it's too easy for somebody break this, including by mistake (named some internal crate "serialize" and issued `cargo publish` by mistake).

If Serde intends to be The Serialization for Rust, it should claim the generic name "serialize" (which may just be a "symlink" to actual Serde).

**Comment by dtolnay** [comment]
> If Serde intends to be The Serialization for Rust, it should claim the generic name "serialize"

I don't agree. If someone comes up with a better (or different) serialization library, let's let them take the name if they want. The crate name `serde` serves us well enough. Even without a symlink, we already show up first for a crates.io search for "serialize": https://crates.io/search?q=serialize

**Comment by erickt** [comment]
Yeah I agree. I like the name serde :) @wycats convinced me it's ultimately better for our community to come up with more interesting names, rather than generic names like `serialize` because not only are names like that not as much fun, they'll always be a better library someday in the future. Cargo supports tagging (and I think fulltext search), so the more popular crates should bubble up over the more generic names, so I'm not too worried about impact if someone else creates a `serialize` crate.

I'm going to close this, but thanks for filing it!
