### ISSUE TITLE
Add conversion between de::Error implementors

### ISSUE THREAD

**Issue by jwilm** [serde-rs/serde#278]
I've got a use case where `deserialize_with` is used to invoke a second deserializer for a different data format. It would be nice to have some From conversion required to map de::Error types from one to another so that try! can be used in such cases. A couple of options

1. Map variants of one type to the other
2. Add a variant which holds Box<de::Error>

**Comment by dtolnay** [comment]
I can't think of anything we can do to improve this. Let us know if you think of anything.

Mapping variants is not something we can do in Serde because these Error types are defined in the individual deserializer libraries, not in Serde. For example: [the one in bincode](https://github.com/TyOverby/bincode/blob/a808c00fb5301742727e2383e16ee3b5377ccd35/src/serde/reader.rs#L37). In fact, nothing in Serde even requires that the Error type is an enum.

We cannot provide something like the following due to coherence rules:

```rust
impl<T, U> From<T> for U where T: serde::de::Error, U: serde::de::Error {
    fn from(err: T) -> U {
        U::custom(err.description())
    }
}
```

We cannot "recommend" that all deserializers provide `impl<T> From<T> for MyError where T: serde::de::Error` because of conflicting implementations.

We cannot do anything like these because Rust doesn't have [CRTP](https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern) (among other reasons):

```rust
trait Error: From<Error> { /* ... */ }
trait Error: for<T: Error> From<T> { /* ... */ }
```

We could do this, but it wouldn't help:

```rust
trait Deserializer {
    type Error: Error + for<'a> From<&'a Error>; // or Box<Error>
}
```
