### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by jimmycuadra** [serde-rs/serde#306]
It would be very helpful if the project included a changelog document, or if the releases on the releases page were given release notes. Right now there isn't an easy way to tell what has changed in each version of serde (and related crates.)

**Comment by dtolnay** [comment]
I have started putting together release notes on the [releases page](https://github.com/serde-rs/serde/releases). I will need @erickt to push a few missing tags ([0.3.3](https://github.com/serde-rs/serde/issues/327), [0.6.7](https://github.com/serde-rs/serde/issues/326), [0.7.4](https://github.com/serde-rs/serde/issues/325)) in order to be able to do those.

**Comment by dtolnay** [comment]
Release notes are on the [releases page](https://github.com/serde-rs/serde/releases). We decided not to add a changelog file - see #329.
