### ISSUE TITLE
Either remove the Travis CI build badge, or make it not point at the `auto` branch

### ISSUE THREAD

**Issue by notriddle** [serde-rs/serde#340]
It's misleading. The contents of your `master` branch are building just fine.

**Comment by dtolnay** [comment]
The badge is actually from the master branch. The master branch does not build right now on nightly because of Clippy: https://github.com/Manishearth/rust-clippy/issues/946

The link is to the most recent build across all branches because Travis doesn't support linking to most recent build on a specific branch: https://github.com/travis-ci/travis-ci/issues/5024

**Comment by dtolnay** [comment]
We could look into adding a branch that tracks master but with the volatile features (like Clippy) disabled, and base the badge on that branch.

**Comment by dtolnay** [comment]
Closing as won't fix because my proposal sounds like a lot of work. We can fix this when Travis supports linking to the most recent build of master.
