### ISSUE TITLE
Fixed size array deserialization

### ISSUE THREAD

**Issue by 0nkery** [serde-rs/serde#391]
Why does deserializer trait delegate fixed size array deserialization to [generic](https://github.com/serde-rs/serde/blob/b5c0406afe9ad1e20616fdb18a2e3f9d7dd40d1e/serde/src/de/mod.rs#L363) method?

**Comment by oli-obk** [comment]
Do you have a concrete use case where this is problematic?

**Comment by 0nkery** [comment]
[Here](https://gist.github.com/iqualfragile/743cc39ac4199e0f669bae13b778474e) is such use case.

[Bincode](https://github.com/TyOverby/bincode) crate cannot deserialize fixed size array. 

This method is not implemented there, so the default method is used for deserialization. It's no wonder it cannot handle this case properly. At the moment bincode just crashes.

**Comment by oli-obk** [comment]
I tried it out locally and can confirm that the bincode examples work when delegating to `deserialize_seq`. Sadly this is a breaking change, because there is the possibility (although unlikely) that someone is depending on this. Then again, the docs sound to me like it should be delegating to `deserialize_seq`, thus this is a bug we can fix even if it's a breaking change?

**Comment by 0nkery** [comment]
I think code relying on bug is a bugged too. :)

**Comment by 0nkery** [comment]
Thanks! Last one question - could you make the new patch release when this PR will be merged?

**Comment by dtolnay** [comment]
https://github.com/TyOverby/bincode/pull/76 fixes this in bincode. We can reopen #392 when we are ready for 0.8.

**Comment by dtolnay** [comment]
I am closing this in favor of #219 which proposes removing all default implementations from the Deserializer trait. That is another way to have prevented the bincode bug.
