### ISSUE TITLE
Fields marked skip_deserializing are ignored even if deny_unknown_fields is set

### ISSUE THREAD

**Issue by sfackler** [serde-rs/serde#444]
I have [this struct definition](https://github.com/sfackler/log4rs/blob/6eea8767b5ed5c014d06685d78a6df8c54147a92/src/file/serde.rs.in#L1-L14). It is configured to derive `Deserialize` and deny unknown fields. I have a field  marked to be skipped, but [the generated implementation](https://github.com/sfackler/log4rs/blob/6eea8767b5ed5c014d06685d78a6df8c54147a92/src/file/serde.rs#L9-L397) appears to [explicitly ignore](https://github.com/sfackler/log4rs/blob/6eea8767b5ed5c014d06685d78a6df8c54147a92/src/file/serde.rs#L347-L350) the skipped field.

I would expect the implementation would treat that field as not even existing, in which case we would see an error if `_p` is referenced in the input being deserialized.

**Comment by dtolnay** [comment]
@oli-obk @erickt opinion on this?

It seems like there are two different use cases for `skip_deserializing`.

1. A field of the struct is not present in the serialized form.
2. A field of the struct is present in the serialized form but should not be deserialized.

If we make this change, there would be no way to handle the second type together with `deny_unknown_fields`.

Maybe we need a second attribute to differentiate the two cases.

**Comment by dtolnay** [comment]
As an initial proposal to iterate on, how about the following change:

- Keep the current behavior of `skip_deserializing` instead of what @sfackler suggests. **"Skip deserializing"** means the field may (or may not) be present in the serialized form, even when using `deny_unknown_fields`.
- Add an attribute `#[serde(not_serialized)]` as the equivalent of the current `#[serde(skip_serializing, skip_deserializing)]` but which behaves the way @sfackler wants when using `deny_unknown_fields`. If a field is **"not serialized"**, it is an error for it to show up when deserializing.

@sfackler please confirm that this would fit your use case.

**Comment by sfackler** [comment]
`#[serde(not_serialized)]` would do what I'm looking for, though it seems confusingly similar to the existing modifiers. In what contexts would someone be looking for the "A field of the struct is present in the serialized form but should not be deserialized." use case?

**Comment by oli-obk** [comment]
> In what contexts would someone be looking for the "A field of the struct is present in the serialized form but should not be deserialized." use case?

When the user doesn't care about the value, but wants to prevent additional fields from being silently ignored through `deny_unknown_fields`, they can do `skip_deserializing`, thus acknowledging that the field is there, but shouldn't trigger the `unknown_fields`

**Comment by sfackler** [comment]
If the user doesn't care about the value, then it seems a bit unfortunate to have to include the field in the struct at all. It seems like something like `#[serde(deny_unknown_fields(allow = "foo"))]` would work better there, right?

**Comment by oli-obk** [comment]
indeed
