### ISSUE TITLE
Allow rename of container with &'static str

### ISSUE THREAD

**Issue by SuperFluffy** [serde-rs/serde#450]
Would it be possible to enable using some `&foo: 'static str` defined in a crate to `#[serde(rename=foo)]`?

For example, I have defined the following constant str:

``` rust
pub const STATISTICS_FIELD: &'static str = "statistics"

#[derive(Deserialize,Serialize)]
pub struct MyStruct {
    #[serde(rename=STATISTICS_FIELD)]
    statistics: MyStatisticsStruct,
    ....
}
```

**Comment by oli-obk** [comment]
Since that would require name resolution, I don't think we'll ever add that. Currently `syntex` does all the heavy lifting, and that works on the AST. It would be very unexpected, if constants in the same module or crate worked, but not constants from other crates

**Comment by dtolnay** [comment]
It isn't about name resolution - the syntax of the language straight-up does not support this. The attribute syntax is extremely limited and `#[serde(rename=STATISTICS_FIELD)]` is just not valid Rust code. If you want this to work, you need to start with a [Rust RFC](https://github.com/rust-lang/rfcs).

**Comment by dtolnay** [comment]
We may be able to do something like `#[serde(rename_const="STATISTICS_FIELD")]`.

**Comment by SuperFluffy** [comment]
Adding to that, `#[serde(serialize_with="$path")]` (and the same for `deserialize_with`) allows for using some function. Why not do the same, but instead of looking for a function, have it look for a `&static str` at `$path`?

**Comment by dtolnay** [comment]
Closing because I don't think this would be a sufficiently common need that it justifies handling it with a new attribute. The workarounds are to either repeat the name in the const + the serde attribute, or use a macro to generate the const based on the serde attribute.

**Comment by davidhewitt** [comment]
A note for those interested in this issue: I believe that the attribute syntax technical limitation no longer applies, so I took a look this morning into how hard it would be for serde to allow attributes like `#[serde(rename = SOME_CONST)]`.

From what I could tell, it wouldn't be _too_ hard to change the rename attribute argument to parse into an enum which is either a `syn::LitStr` or `syn::Ident`. But the challenge after that is that the downstream code in the derive macros is built on the fact these attributes are currently literal strings. For example the macros check the serialized field names do not conflict with the variant tag field name, which becomes impossible to do if the name is some transparent ident instead of a literal passed to the macro.

Perhaps if const assertions were a thing, the macro could emit compile-time assertions as part of the `#[derive(Serialize)]` impl and let the compiler resolve whether the field name and the tag name are the same. But that's a future 🚀 Rust feature.

**Comment by 9999years** [comment]
We have const panic assertions now with 1.57, so this is unblocked. I'll see if I can work on this.

**Comment by wdanilo** [comment]
Hi! I believe this should not be closed. This would be a very useful thing and since Rust now allows this syntax, I think we should re-open this ticket :)

**Comment by BratSinot** [comment]
Any update on this?
