### ISSUE TITLE
Annotations behind cfg_attr aren't generated.

### ISSUE THREAD

**Issue by Aaronepower** [serde-rs/serde#463]
[Sample Project](https://github.com/Aaronepower/rust-test)

Serde_codegen leaves in cfg_attrs with `serde` in them causing compile errors.

```
#[cfg_attr(feature = "serde_feature", derive(Debug, Deserialize))]
struct Foo {
    #[cfg_attr(feature = "serde_feature", serde(skip_deserializing))]
    vec: Vec<u8>,
}
```

**Comment by dtolnay** [comment]
Thanks for the sample repo.

I don't know how we can fix this. @oli-obk @erickt? We can extend the [attribute stripping](https://github.com/serde-rs/serde/blob/b6ed82dd7d46ec4a69f3b4fad64b5eedd045875c/serde_codegen/src/lib.rs#L53-L56) to filter out `#[cfg_attr(*, serde(*))]`, I am not worried about that. But how do we get serde_codegen to process the `cfg_attr`'d attributes? AFAIK we don't have a way to evaluate cfg expressions.

@Aaronepower until we figure this out, one (admittedly not great) workaround is to use `cfg` instead of `cfg_attr`:

```rust
#[cfg(feature = "serde_feature")]
#[derive(Debug, Deserialize)]
struct Foo {
    #[serde(skip_deserializing)]
    vec: Vec<u8>,
}

#[cfg(not(feature = "serde_feature"))]
struct Foo {
    vec: Vec<u8>,
}
```

**Comment by dtolnay** [comment]
Closing as won't fix because nobody knows how to fix it and the problem will go away with Macros 1.1.

**Comment by rsalmei** [comment]
Hello!
Please, did the problem go away today?
I'm with exactly this problem, and I don't know what to do, thanks!
