### ISSUE TITLE
Stack overflow compiling serde_codegen 0.8 on OSX nightly

### ISSUE THREAD

**Issue by alexcrichton** [serde-rs/serde#486]
I've been seeing some [failures](https://travis-ci.org/alexcrichton/backtrace-rs/jobs/150823832) in compiling `serde_codegen` on Travis OSX builders using the nightly compiler:

```
   Compiling serde_codegen v0.8.0

error: failed to run custom build command for `serde_codegen v0.8.0`

process didn't exit successfully: `/Users/travis/build/alexcrichton/backtrace-rs/target/debug/build/serde_codegen-bb1ef080fae9a50a/build-script-build` (signal: 6, SIGABRT: process abort signal)

--- stderr

thread 'main' has overflowed its stack

fatal runtime error: stack overflow
```

I wonder, is the build script for serde-codegen doing anything that might cause this? This started regressing for me about the time MIR codegen landed, and there's a few known stack-space issues with MIR, but for now could an explicitly large stack be used perhaps?

**Comment by alexbool** [comment]
Hmm, I am using serde 0.8 with nightly and MIR on OS X for a while and have never run into this.

**Comment by oli-obk** [comment]
@alexcrichton the serde-codegen build script parses the entire crate with quasi and then expands the quasi macros. Increasing the stack size would be easy (pack everything in a thread and set the RUST_MIN_STACK env var), but I have no way of testing it. I could simply pack everything in a thread and you can experiment with the RUST_MIN_STACK env var yourself. Once that works, I can add code that sets the RUST_MIN_STACK var to a value you have found to work (as long as it isn't already set).

@alexbool I'm not sure whether Rust chooses the main thread's stack size depending on some system information, maybe it differs between your setup and @alexcrichton's.

The difference might also be because of some compiler options. debug mode + no optimizations will obviously use more stack space than release mode + optimizations.

**Comment by alexcrichton** [comment]
Yeah unfortunately I've been unable to reproduce locally as well, it's only reproducing on Travis. It may be the case that https://github.com/rust-lang/rust/pull/35409 fixes this, but in the meantime using `RUST_MIN_STACK` works for me!

**Comment by oli-obk** [comment]
Wait... It works without the changes or it should work with them?

**Comment by alexcrichton** [comment]
Oh it doesn't work yet, I was gonna wait for a merge so I can test out

**Comment by oli-obk** [comment]
oh, good, that would have been weird.

I published 0.8.1 which does all the syntex stuff in a thread, so hopefully `RUST_MIN_STACK` works.

**Comment by alexcrichton** [comment]
Worked for me, thanks!

**Comment by oli-obk** [comment]
Great
