### ISSUE TITLE
Implementing deserializers with serde-rs

### ISSUE THREAD

**Issue by Relrin** [serde-rs/serde#537]
I'm going to write BERT deserializer for the `Vec<u8>` type and I have few questions about implementing deserializers with serde-rs:

- Does serde-rs have a common approach to implement this stuff? Different extensions(or plugins) have a different implementation of deserialize mechanism. For example, I overlooked JSON/YAML/CBOR extensions. Theirs codebase very different and its looks like serde-rs don't specify "how to" make it in the right way.
- Existing plugins have a `forward_to_deserialize` macro, which different of each other. When and where necessary to using it? Does it required for deserializers?
- Don't understand where to start my implementation. [Serde docs](https://serde.rs/impl-deserialize.html) let me "sketchy understanding" that need to override trait (like to the `ser::Serialize`?). What to do with `parse_*` methods? When and where are the calling? For which cases shall I to use them?

**Comment by oli-obk** [comment]
> Theirs codebase very different and its looks like serde-rs don't specify "how to" make it in the right way.

There's no good way to specify anything, because every serialization format has its own quirks. We explicitly moved away from supporting json-like formats by default, and requiring formats to implement all methods.

> Existing plugins have a forward_to_deserialize macro, which different of each other. When and where necessary to using it? Does it required for deserializers?

due to the mentioned change that all methods need to be implemented, certain formats that don't really need all that knowledge about the exact type now need to forward all their methods to the `deserialize` method. For a binary format that is not helpful, you need to implement all methods (and error out on those that you do not support).

You need to implement the `Deserializer` trait for a `BertDeserializer` type (or any other name) that you created. That type needs access to the `&[u8]` from which you extract your values.

> What to do with parse_* methods?

We have `parse_*` methods? not sure what you mean.

> For which cases shall I to use them?

A `Deserializer` does not call any methods, its methods get called.

**Comment by Relrin** [comment]
Thanks for the explanation! 😊

> due to the mentioned change that all methods need to be implemented, certain formats that don't really need all that knowledge about the exact type now need to forward all their methods to the deserialize method. For a binary format that is not helpful, you need to implement all methods (and error out on those that you do not support).

As far as I understand this macro is usefull when I don't want to implement unsupported methods? And for each other which are supported by BERT better to specify manually?

> We have `parse_*` methods? not sure what you mean.

For example take the [CBOR deserializer](https://github.com/pyfisch/cbor/blob/master/src/de.rs#L50-L64). This module have a lot of different parse_* methods. Function `parse_value` it is a main function, which called by deserializer and using for make a hint about passed data, right? 

> A `Deserializer` does not call any methods, its methods get called.

How can I then to make a hint for a deserializer to which types necessary to convert all passed data?

**Comment by oli-obk** [comment]
> How can I then to make a hint for a deserializer to which types necessary to convert all passed data?

My brain was still on vacation.

You can obviously call all methods that the `Visitor` object passed to the method offers, and all methods you implement on your deserializer type.

> This module have a lot of different parse_* methods. Function parse_value it is a main function, which called by deserializer and using for make a hint about passed data, right? 

That's just a design chosen by CBOR. Feel free to copy it if it fits your needs close enough.

> As far as I understand this macro is usefull when I don't want to implement unsupported methods? And for each other which are supported by BERT better to specify manually?

No.

All methods except for `deserialize` are there as hints from the type to the `Deserializer` about what kind of value the object of that type expects. So if you don't support a method, you need to return an error. If you don't care about the hint, because your format specifies its types in the format itself, then you can just forward all methods to `deserialize`, that is what the macros do.

**Comment by Relrin** [comment]
Thanks a lot for your help.
