### ISSUE TITLE
Impl Serialize/Deserialize for !

### ISSUE THREAD

**Issue by tikue** [serde-rs/serde#544]
`Serialize` is straightforward. As for `Deserialize`, I guess it would just panic? This is useful for me when serializing and deserializing types like `Result<T, !>`.

**Comment by dtolnay** [comment]
If we do `Deserialize for !` it should error, not panic.

Is `Result<T, !>` the only instance where you need this? Would it make more sense to specialize De/Serialize for `Result<T, !>` instead of implementing them for `!`? `Result<T, !>` is equivalent to T so we might as well serialize it the same way.

**Comment by tikue** [comment]
The `Result<T, !>` was actually a simplified example. My actual use case involves an error type where one variant is generic: the actual type being deserialized is `Result<T, Error<!>>`. Basically, if a user implements a service that can never return an application error, the application error is `!`, and the framework error is `Error<!>`.

**Comment by tikue** [comment]
That being said, it could definitely make sense to specialize the `Result<T, !>` case as well!
