### ISSUE TITLE
impl<T> Serialize for Iterator<T> ? 

### ISSUE THREAD

**Issue by Cobrand** [serde-rs/serde#571]
it would be nice to be able to do something like this : 

```
let v = vec![1,7,3,5,9];
let string = serde_json::to_string(v.iter().filter(|value| value > 3))
```

Don't you think ?

If no one is against it I will implement this by next week (and open a PR as needed)

**Comment by dtolnay** [comment]
Rust will allow you to write `impl<T> Serialize for Iterator<Item = T>` but it will only apply to Iterator trait objects (in practice, only `&Iterator<Item = T>` and `Box<Iterator<Item = T>>`) not the iterator in your example.

```
let string = serde_json::to_string(&v.iter().filter(|&&value| value > 3));
                         ^^^^^^^^^ trait `std::iter::Filter<std::slice::Iter<'_, {integer}>, [closure@test.rs:24:32: 24:51]>: serde::Serialize` not satisfied
```

The correct impl would be `impl<T, I> Serialize for I where I: Iterator<Item = T>, T: Serialize` but it conflicts with at least one existing impl:

```
117 | impl Serialize for String {
    | - first implementation here
...
128 | impl<T, I> Serialize for I where I: Iterator<Item = T>, T: Serialize {
    | ^ conflicting implementation for `std::string::String`
```

I am keeping this open because there may be something we can do to make this better (especially when specialization is stable) but it probably won't be as simple as `impl<T> Serialize for Iterator<T>`.

**Comment by Cobrand** [comment]
You are right, it was just an idea I didn't think about the actual impl too much. I didn't realize that it would conflict with others impls, too. I guess this will be on hold until specialization hits stable.

**Comment by jmesmon** [comment]
One could possibly provide a wrapper type to do this serialization:

```
struct SerializeIterator<T: Serialize, I: Iterator<Item = T>>(a: I);
impl<T, I> Serialize for SerializeIterator<T, I> where I: Iterator<Item = T>, T: Serialize { ... }
```

(though choosing a more convenient name or using a extension trait for construction might be preferable)

This isn't perfect because it makes handling structures containing iterators that aren't top level (and it isn't very composable if one requires other trait impls), but it might still be useful to have.

**Comment by bluss** [comment]
It would be very useful to have an iterator wrapper, it's recurring thing that an implementation will use when implementing the traits manually. It's only intended as a one-off wrapper, other trait impls are not needed. ([My example.](https://github.com/bluss/rust-ndarray/blob/75aa62a57391eceb675248aa0d1bf7a9794a613b/src/array_serde.rs#L30-L36))

**Comment by oli-obk** [comment]
We could also implement `Serialize` for `libstd`'s Iterator adaptors, which would at least simplify the common cases.

**Comment by oli-obk** [comment]
serde master has now `serde::ser::iterator`, which is a function that turns an iterator into a `Serialize` that can be used anywhere and will serialize as a sequence. If the length is exact (`Some(iter.size_hint().0) == iter.size_hint().1`, the serialized sequence will get a length, if it is not exact, the length will be `None`. This might cause runtime errors in case the targeted `Serializer` does not support unknown length sequences.

The function is available if the `unstable` feature of serde is activated. Feedback is welcome.

**Comment by dtolnay** [comment]
This is superseded by [`Serializer::collect_seq`](https://docs.serde.rs/serde/ser/trait.Serializer.html#method.collect_seq) added in #736.

**Comment by bluss** [comment]
Just talking, but I miss the composable form of using a value, like if we have a convenience type like "Iter" and use something like

```rust
        state.serialize_field("nodes", &Iter::new(self.raw_nodes().iter().map(|n| &n.weight)))?;
        state.serialize_field("edges", &Iter::new(self.raw_edges().iter()))?;
```

Where one doesn't have to make new types for each field that is a sequence from a iterator.

**Comment by pmi-spease** [comment]
This doesn't fix the issue of trying to use an iterator with something that requires a Serialize trait.

For instance, the askama templating library uses serde to build JSON representations of data:
```
#[derive(Template)]
#[template(path = "chart.html")]
struct ChartTemplate<I> where I: IntoIterator<Item=DataPoint> + ::serde::Serialize {
    dataPoints: I,
}

#[derive(Serialize)]
struct DataPoint {
    x: f64,
    y: f64,
}

fn stream_chart_page(data: impl IntoIterator<Item=DataPoint> + serde::Serialize) -> BackendResult<impl Responder<Item=HttpResponse>> {
    Ok(ChartTemplate { dataPoints: data })
}
```

You're still forced to generate a Vec to pass to this instead of being able to pass an iterator chain directly.

**Comment by cjhopman** [comment]
> This is superseded by Serializer::collect_seq added in #736.

This is too bad. As the previous comment noted this doesn't fix the issue of trying to use an iterator where a Serialize trait impl is required. SerializeSeq itself requires a Serialize trait for each element and so if you have some nested sequence you run into that same unergonomic case of wanting a Serialize impl for Iterator<T>.

**Comment by jamespfennell** [comment]
> This is too bad. As the previous comment noted this doesn't fix the issue of trying to use an iterator where a Serialize trait impl is required. SerializeSeq itself requires a Serialize trait for each element and so if you have some nested sequence you run into that same unergonomic case of wanting a Serialize impl for Iterator.

In this case can you call [`std::iter::Flatten`](https://doc.rust-lang.org/std/iter/struct.Flatten.html) on the nested iterator to get a flat iterator of serializable things?

In general I think that, yes, the solution of using [`Serializer::collect_seq`](https://docs.serde.rs/serde/ser/trait.Serializer.html#method.collect_seq) doesn't make things _trivial_, but when designing a big library like serde it seems like making every possible use case trivial isn't ideal.
