### ISSUE TITLE
Document differences between 'serialize_map' and 'serialize_struct'

### ISSUE THREAD

**Issue by frewsxcv** [serde-rs/serde#639]
Someone in #rust-beginners on IRC asked about the differences, and the API documentation doesn't make it very obvious. If I knew the differences, I'd be happy to open a PR :)

**Comment by NfNitLoop** [comment]
It was me!

For example -- if I write my own serialization for a struct, and use it with serde_json, the resulting JSON is the same whether I use serialize_map or serialize_struct.

Is one more efficient than the other? (My bet would be struct, which can rely on the keys being `&str`?)  Is one preferable to the other?  what do the `name` and `len` parameters mean for `serialize_struct()`?  (The name seems unused in JSON output. is len the number of elements? Why is that necessary)

And these are just questions off the top of my head.  :p   A high-level summary would be super helpful, along the lines of: "here are the abstract types that Serde can handle, and how they might map to a couple example output formats."

**Comment by NfNitLoop** [comment]
@frewsxcv Oh! There are docs here: https://serde.rs/impl-serialize.html

Maybe it's enough to link to those docs from the Rustdocs? I didn't know they existed.

That page seems to imply that, if you're serializing a struct, you should just use user `serialize_struct`. Though, I'm still not sure what the `name` and `len` params are used for. Maybe `name` is for XML tags?

**Comment by dtolnay** [comment]
Not all data formats are going to use all the information. JSON in particular does not use the name and len (number of fields) of the struct, as you observed.

As an example of something that does use the name, consider implementing `serde_rust` which will serialize a data structure into the corresponding Rust source code to build the data structure. So if you have a type which is `struct S { a: u8 }` then it might serialize an instance of S as `"S { a: 0 }"`.

The difference between serializing maps vs structs is that when you deserialize a struct, you are expected to know what the fields are without looking at the input data. You can see this in the signature of `Deserializer::deserialize_struct`. The same is not true for maps - the input data will determine what the keys are. As you know, JSON doesn't distinguish between these cases. There are other formats that do, for example Bincode which is a compact binary data format. When serializing a map it will put both the keys and the values into the binary data. When serializing a struct it will serialize just the values in order to save space and improve performance.

I agree this stuff needs to be covered more thoroughly in the rustdoc and serde.rs. Thanks for filing a ticket!

**Comment by dtolnay** [comment]
I clarified this in the docs that will be released along with the next version of Serde.
