### ISSUE TITLE
Tokio

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#654]
I only very recently started paying attention to Tokio so someone with more experience should chime in. Is there anything we can provide in Serde or in a helper crate to make Serde compose well with Tokio? Where do we fit in, if at all?

**Comment by dgriffen** [comment]
I've recently been using Tokio and Serde together in a project of mine. As far as I can tell Serde already works quite well with Tokio. Since serializing and deserializing returns a result it is already composable with futures and streams. As long as I'm not missing something and those operations are secretly blocking I don't think there is much to do.

Someone else might have a more uncommon use-case that doesn't work well. But I haven't run into any yet.

**Comment by dtolnay** [comment]
Nice! Thanks for the feedback. We'll just keep doing what we're doing then.

**Comment by vorner** [comment]
Serde works if you know the size of the message in advance ‒ if you have a length prefix, or the messages are newline delimited. But if the length of message is known only by parsing it, then it is a bit worse.

The problem is, with tokio you get data in chunks, which it can buffer for you. But the chunks don't have to be on a message boundary. One thing that'd help is knowing how many bytes of input were consumed decoding a message, so the prefix of the buffer can be dropped. It would then be similar to how example which splits the input into lines:

https://tokio.rs/docs/getting-started/simple-server/#implement-codec

As suggested on IRC, there's a workaround for this: https://github.com/serde-rs/json/issues/183.

The other option is something like `StreamDeserializer` in serde_json, but working on top of Futures' Stream instead of an Iterator. The difference is, Stream can return `NotReady`, which means no more data is available *for now*, but may be available later. The Deserializer would return `NotReady` as well. But once it would get called again, it would try to resume from the same place. The problem with StreamDeserializer is that it expects the iterator inside to block/run to the end or return an error, but that error means the end.

**Comment by conradev** [comment]
Yes. You can actually map a `Stream` of `Vec<u8>` chunks directly into an `Iterator` using `wait` but the problem with that is that it blocks the thread. This can cause the thread to deadlock if the `StreamDeserializer` is waiting on the `Stream`, but the event loop needs to be polled for the `Stream` to produce more data.

There could definitely be a version of `StreamDeserializer` that works nicely with `Stream`s (push rather than pull).
