### ISSUE TITLE
Document serialize_struct example

### ISSUE THREAD

**Issue by dbrgn** [serde-rs/serde#658]
The docs for custom serialization (https://serde.rs/impl-serialize.html) say the following about custom struct serialization:

> // An ordinary struct. Use three-step process:
> //   1. serialize_struct
> //   2. serialize_struct_elt
> //   3. serialize_struct_end

But there is no example that shows how to actually use serialize_struct.

I can probably try to implement it in a similar way as explained in the "Serializing a sequence or map", but separate docs would be great :)

**Comment by dtolnay** [comment]
Good call, we definitely need an example here. For now here is one from our codebase:

https://github.com/serde-rs/serde/blob/v0.8.21/serde/src/ser/impls.rs#L625-L634

```rust
impl Serialize for Duration {
    fn serialize<S>(&self, serializer: &mut S) -> Result<(), S::Error>
        where S: Serializer,
    {
        let mut state = try!(serializer.serialize_struct("Duration", 2));
        try!(serializer.serialize_struct_elt(&mut state, "secs", self.as_secs()));
        try!(serializer.serialize_struct_elt(&mut state, "nanos", self.subsec_nanos()));
        serializer.serialize_struct_end(state)
    }
}
```

This is a bit unusual in that it is getting the field values from method calls because [`Duration`](https://doc.rust-lang.org/time/time/struct.Duration.html) does not expose the fields publicly. For a struct in your own crate it would probably serialize `self.secs` instead of `self.as_secs()`.

**Comment by dbrgn** [comment]
This section in the docs probably needs a reference to `serialize_map` too. See also: #639 and #708.

**Comment by dtolnay** [comment]
Thanks! I added an example in https://github.com/serde-rs/serde-rs.github.io/commit/fa2c106a3faa974b32cce051e40b869da35d66f7.
