### ISSUE TITLE
Use serde for ffi

### ISSUE THREAD

**Issue by Yamakaky** [serde-rs/serde#727]
Do you think it would be possible to use serde to encode and decode structs for ffi? For example, convert between pointers and references, `*const *const char` to `&[str]`... That last example makes me think that it would not be possible, as you often have a field with the length and another with the pointer.

**Comment by oli-obk** [comment]
I think specialized functions would be more appropriate, especially due to the unsafe nature. Serde was not written with `unsafe` in its mind. So there might be different `Serialize` and `Deserialize` impls which break serde's rules, but that usually just causes an `Err` or a `panic!`, but no unsafety.

**Comment by Yamakaky** [comment]
Ok
