### ISSUE TITLE
Tagged enums don't complain if one of the variants contains a field with the same name as the tag

### ISSUE THREAD

**Issue by Arnavion** [serde-rs/serde#750]
```rust
extern crate serde;
#[macro_use]
extern crate serde_derive;
extern crate serde_json;

#[derive(Serialize)]
#[serde(tag = "version")]
enum Foo {
    V1(Foov1),
}

#[derive(Serialize)]
struct Foov1 {
    version: String,
}

fn main() {
    println!("{}", ::serde_json::to_string_pretty(&Foo::V1(Foov1 { version: "Hi".to_string() })).unwrap());
}
```

```json
{
    "version": "V1",
    "version": "Hi"
}
```

It would be nice to get a compile-time error for this.

Edit: Or atleast a runtime error.

**Comment by dtolnay** [comment]
I don't think there is anything we can do to detect this case at compile time. During macro expansion when #[derive(Serialize)] on Foo runs, there is no way to know the definition of Foov1.

As for runtime, duplicate keys is not something we have tried to detect in the past - this is not new with internally tagged enums. For example the following code produces the same output.

```rust
extern crate serde;
extern crate serde_json;

use std::collections::BTreeMap;
use serde::{Serialize, Serializer};

#[derive(Eq, PartialEq, Ord, PartialOrd)]
struct K(u8);

impl Serialize for K {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
        where S: Serializer
    {
        serializer.serialize_str("version")
    }
}

fn main() {
    let mut map = BTreeMap::new();
    map.insert(K(0), "V1");
    map.insert(K(1), "Hi");

    println!("{}", serde_json::to_string_pretty(&map).unwrap());
}
```

Catching this at runtime could easily be a 10x or more performance penalty.

One thing we could detect at compile time is this:

```rust
#[derive(Serialize)]
#[serde(tag = "version")]
enum Foo {
    V1 {
        version: String, // conflicts with tag
    }
}
```

Do you think this problem is common enough and hard enough to debug that Serde needs to handle it? I figure once you see two "version" keys it's pretty easy to tell how it happened.

**Comment by Arnavion** [comment]
>During macro expansion when #[derive(Serialize)] on Foo runs, there is no way to know the definition of Foov1.

Yeah, I figured this would be a problem.

>One thing we could detect at compile time is this

That would be nice. In my case I do need it to be a newtype variant of a separate struct instead of a struct variant, but it might prevent other users from tripping on it.

>Do you think this problem is common enough and hard enough to debug that Serde needs to handle it?

Atleast for now I haven't hit this issue in my code; I constructed this case only out of curiosity to see what would happen. So if it's too hard / unperformant to detect this, I personally think it's fine to leave it broken.

>I figure once you see two "version" keys it's pretty easy to tell how it happened.

Well, that isn't consistent either :) 

```rust
    println!("{}", ::serde_yaml::to_string(&Foo::V1(Foov1 { version: "Hi".to_string() })).unwrap());
```

```yml
---
version: Hi
```

which might go undetected for longer.
