### ISSUE TITLE
Cow<str> and Cow<[u8]> should support implicit borrow

### ISSUE THREAD

**Issue by xfix** [serde-rs/serde#928]
Currently `Cow` type automatically owns data, which is a silent performance trap, considering people may think that `Cow<str>` should borrow when possible (but only `&str` and `&[u8]` currently do). There is a workaround for this creating a newtype from `Cow<str>` that specifies `#[serde(borrow)]`, but it's ugly.

```rust
#[macro_use]
extern crate serde_derive;
extern crate serde_json;

use std::borrow::Cow;

#[derive(Deserialize)]
struct CowStr<'a>(#[serde(borrow)]
                  Cow<'a, str>);

fn main() {
    let json = r#""Hello, world""#;
    let example: CowStr = serde_json::from_str(json).unwrap();
    println!("{}", match example.0 {
        Cow::Borrowed(_) => "borrowed",
        Cow::Owned(_) => "owned",
    });
}
```

**Comment by oli-obk** [comment]
This is hard to do, because there's no way to detect the `Cow` type in a deterministic manner. I could write a clippy lint which detects when you do `derive(Deserialize)` on a struct with a `Cow` in it, but without a `#[serde(borrow)]` attribute on said `Cow`.

**Comment by dtolnay** [comment]
@oli-obk we already have detection for `Cow` types [here](https://github.com/serde-rs/serde/blob/v1.0.4/serde_derive_internals/src/attr.rs#L1093).

@xfix this is intentional because in my experience I more often want Cow to copy the data when deserializing. I believe this is a better default than making the following program fail to compile (try adding `#[serde(borrow)]`).

```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
extern crate serde_json;

use std::borrow::Cow;

#[derive(Serialize, Deserialize, Debug)]
struct Xfix<'a> {
    s: Cow<'a, str>,
}

fn run() -> Result<Xfix<'static>, serde_json::Error> {
    let xfix = Xfix { s: Cow::Borrowed("\n\n\n") };
    let s = serde_json::to_string(&xfix)?;
    println!("{}", s);

    let de: Xfix = serde_json::from_str(&s)?;
    println!("{:?}", de);
    Ok(de)
}

fn main() {
    run().unwrap();
}
```

It also means we have a single consistent way to opt into borrowing, rather than a way to opt into borrowing and a way to opt out of borrowing.

**Comment by oli-obk** [comment]
> @oli-obk we already have detection for Cow types here.

I thought we did, but I didn't know about

> more often want Cow to copy the data when deserializing
