### ISSUE TITLE
Do not serialize optional fields with a container attribute

### ISSUE THREAD

**Issue by vityafx** [serde-rs/serde#947]
I know about field attribute

```rust
#[serde(skip_serializing_if = "Option::is_none")]
```

But it is very common, for example, for json, not to serialize fields if they are empty. I have big structures with many optional types and it is very noisy to add this attribute to each of these fields. I propose to add one container attribute instead:

```rust
#[serde(skip_optionals)]
pub struct A {
    pub field: Option<i64>,  // will not be serialized as same as if skip_serializing_if = "Option::is_none"
}
```

**Comment by Enet4** [comment]
This is opportune, since there have been a few questions lately on SO around using serde with optional or null-like fields [[1](https://stackoverflow.com/q/44331037/1233251), [2](https://stackoverflow.com/q/44205435/1233251), [3](https://stackoverflow.com/q/44301748/1233251)]. This includes a question of your own,  it seems. :slightly_smiling_face: 

I wouldn't be against a new attribute to make this use case a bit more elegant. The more I think of it, the more I realize how hard it is to come up with a good one. Nonetheless, `skip_optionals` seems to work fine, with the drawback that it cannot represent mandatory fields with optional values (for instance: a field that can be either `string` or `null` in JSON, but must not be missing). It also won't work with the solution [here](https://stackoverflow.com/a/44332837/1233251), where a custom type was used.

With all this in mind, I'm certainly interested in hearing from the Serde developers on this subject. :slightly_smiling_face:

**Comment by oli-obk** [comment]
The problem is that we have no clue which fields have what type. This is similar to the serde borrow attribute. We only get a textual representation of the types. But that could be anything... a newtype with the same name, or a type alias, or some random type which looks like a known type.

We could do some best effort thing where we try to do the right thing for vec, option, boxed slice, string...

**Comment by vityafx** [comment]
@oli-obk I don't quite understand what are you gonna say. With `syn` crate it is very easy to enumerate fields of a struct with their types. So, we do that and mark all the options with a boolean flag which says "skip serialization if it is Option and such key was not present in the json". I will do that by myself.

**Comment by dtolnay** [comment]
The concern was things like:

```rust
type MaybeString = Option<String>;

#[derive(Serialize)]
#[serde(skip_optionals)]
struct Vityafx {
    name: MaybeString,
}
```

It would be unfortunate to factor out the type of a field into a `type` declaration (which is never a breaking change) and realize later that it broke serialization because the field no longer looks like an Option.

**Comment by dtolnay** [comment]
In any case, I would be okay with adding a container attribute that does the best-effort version of this.

**Comment by vityafx** [comment]
@dtolnay oh, okay, now I agree that this would be difficult to implement since we don't know what the real type is (if `syn` crate gives only name of the type as `String`)... Is there any chance to extend `syn` in that way?

**Comment by oli-obk** [comment]
@vityafx it is not a limitation of syn, but of the procedural derive macros offered by rustc. This won't change in the near future, but there are vague plans to improve it someday. I'm not sure if things like this will ever work, but there will be some improvements.

**Comment by dtolnay** [comment]
It is not possible to solve in general, and I don't know of any vague plans that involve this. You might have a derive like:

```rust
#[derive(Wow)]
struct Vityafx {
    name: MaybeString,
}
```

where the output of the derive is:

```rust
type MaybeString = Option<String>;
```

So in general it is impossible to know the type of anything until after macro expansion is all done. There is no API you could invent that would tell you the type of MaybeString because that type is defined later on by the macro.

**Comment by oli-obk** [comment]
I meant improving the derive macros to not work on strings anymore and having some form of communication with the compiler other than "please dump this text somewhere near the type declaration you gave me". No clue whether that will ever help in cases like these.

**Comment by Diggsey** [comment]
Wouldn't it be possible to implement this with specialization:

```
trait ShouldSkip { fn should_skip(&self) -> bool }
impl<T> ShouldSkip for T {
    default fn should_skip(&self) { false }
}
impl<T> ShouldSkip for Option<T> {
    fn should_skip(&self) { self.is_none() }
}
```

Now you can implement the attribute as just adding `#[serde(skip_serializing_if = "ShouldSkip ::should_skip")]` to *all* the fields, regardless of their type.

**Comment by salim7** [comment]
Is there any update on this issue? I think Diggsey's suggestion could be used in combination with the initial suggestion of using `#[serde(skip_optionals)]` on the struct to achieve our goal perfectly :-)

**Comment by mmstick** [comment]
Also adding a ping here, as we use Rust and "JSON:API" at System76. Some JSON resources in our inventory system have dozens of possible attributes, most of which are `Option<T>` and should not be included during serialization.

**Comment by Kampfkarren** [comment]
+1, All of my structures use Option fields and creating a custom type for it is extremely noisy.

**Comment by dtolnay** [comment]
I would prefer for this to be handled by an attribute macro in a different library. I posted a request for implementation in https://github.com/dtolnay/request-for-implementation/issues/18.

**Comment by doivosevic** [comment]
+1 for this feature

**Comment by leebenson** [comment]
https://docs.rs/serde_with/latest/serde_with/attr.skip_serializing_none.html
