### ISSUE TITLE
Rename with function

### ISSUE THREAD

**Issue by ordian** [serde-rs/serde#952]
Is it possible to write a generalized rename/rename_all attribute, which will accept any function :: &str -> String as a parameter? E.g.
```rust
#[derive(Serialize, Deserialize)]
#[serde(rename_all(with = "prefix_request"))]
enum Request {
   Register,
   Unregister,
}

fn prefix_request(s: &str) -> String {
    "Request".to_string() + s
}
```

**Comment by clarcharr** [comment]
Not possible due to the way that derives work.

**Comment by ordian** [comment]
@clarcharr why do you think so?
See e.g. [validate](https://github.com/Keats/validator).

**Comment by clarcharr** [comment]
@ordian `validate` works because the functions are only used in the generated code; this would require the functions *to* generate the code.

Essentially, you can't use functions outside the derive logic to create the derive logic, unless you were to run the function every serialize/deserialize (which seems impractical)

Might make sense to have a `rename_prefix`/`rename_suffix` option though!

**Comment by ordian** [comment]
@clarcharr 
> unless you were to run the function every serialize/deserialize (which seems impractical)

well, in this case we can use lazy_static or, maybe, if it's possible, instead of function pass macro, e.g.
```rust
#[derive(Serialize, Deserialize)]
#[serde(rename_all(with = "add_prefix_foo!"))]
enum Request {
   Register,
   Unregister,
}
```

**Comment by dtolnay** [comment]
I would prefer to solve this use case with handwritten Serialize and Deserialize impls rather than introducing a new serde attribute. Maybe a serde helper crate like [serde-aux](https://crates.io/crates/serde-aux) or [serde_with](https://crates.io/crates/serde_with) could provide a macro to help generate the impls for this case.
