### ISSUE TITLE
Expose `serde::private::de::missing_field` to make it easier for custom Deserialize impls to have that behavior.

### ISSUE THREAD

**Issue by ahmedcharles** [serde-rs/serde#996]
I think the title says it all.

**Comment by Marwes** [comment]
In `serde_state` I needed to modify it to work with `DeserializeSeed` so it may be worth extending it for that usecases or adding a `*_seed` function before stabilizing if that is desired

**Comment by dtolnay** [comment]
Custom Deserialize impls should not need missing_field. The derive(Deserialize) only needs it because there is no way for it to tell which fields are Option\<_\> during macro expansion.

Here is what [Manually implementing Deserialize for a struct](https://serde.rs/deserialize-struct.html) would look like with optional fields:

```diff
fn visit_map<V>(self, mut map: V) -> Result<Duration, V::Error>
    where V: MapAccess<'de>
{
    let mut secs = None;
    let mut nanos = None;
    while let Some(key) = map.next_key()? {
        match key {
            Field::Secs => {
                if secs.is_some() {
                    return Err(de::Error::duplicate_field("secs"));
                }
                secs = Some(map.next_value()?);
            }
            Field::Nanos => {
                if nanos.is_some() {
                    return Err(de::Error::duplicate_field("nanos"));
                }
                nanos = Some(map.next_value()?);
            }
        }
    }
-   let secs = secs.ok_or_else(|| de::Error::missing_field("secs"))?;
-   let nanos = nanos.ok_or_else(|| de::Error::missing_field("nanos"))?;
    Ok(Duration::new(secs, nanos))
}
```

**Comment by ahmedcharles** [comment]
I used this when writing a macro which effectively did `#[derive(Deserialize)]`, only differently. So, yes, if you are manually implementing `Deserialize` for a specific thing, then you can know if something is optional. But that's not the use case I was intending with this request.

**Comment by dtolnay** [comment]
Ah that makes sense. I think this is part of a broader discussion around how to simplify the process of writing Deserialize impls in general. Just exposing missing_field would not make Deserialize easy to implement correctly, so I would prefer to leapfrog that and provide a better alternative instead.

It would help to understand how your generated implementations of Deserialize are different from serde_derive's ones. Can you come up with some ways that [this Deserialize impl](https://serde.rs/deserialize-struct.html) could be expressed in 10 lines instead of 50+ lines while also being applicable to your macro?

**Comment by ahmedcharles** [comment]
I did it as part of: https://github.com/amethyst/amethyst/pull/258/commits/8f216cca93ebd71a5e617ebe3a3609ebfd9bca19

I'm not entirely sure about the higher level picture at the moment. I'll give it some thought.
